import { BibleBook } from "../../entities/bible-book.entity";

export const BIBLE_BOOKS: BibleBook[] = [
  BibleBook.make({
    name: "Genesis",
    author: "es",
    description: "The book of beginnings, creation, and the patriarchs",
    firstChapter: 1,
    lastChapter: 50,
    fullName: "The First Book of Moses:  Called Genesis",
  }),
  BibleBook.make({
    name: "Exodus",
    author: "es",
    description: "The deliverance of Israel from Egypt",
    firstChapter: 1,
    lastChapter: 40,
    fullName: "The Second Book of Moses:  Called Exodus",
  }),
  BibleBook.make({
    name: "Leviticus",
    author: "ses",
    description: "Laws and rituals for Israel's worship",
    firstChapter: 1,
    lastChapter: 27,
    fullName: "The Third Book of Moses:  Called Leviticus",
  }),
  BibleBook.make({
    name: "Numbers",
    author: "ses",
    description: "Israel's wandering in the wilderness",
    firstChapter: 1,
    lastChapter: 36,
    fullName: "The Fourth Book of Moses:  Called Numbers",
  }),
  BibleBook.make({
    name: "Deuteronomy",
    author: "ses",
    description: "Moses' final words to Israel",
    firstChapter: 1,
    lastChapter: 34,
    fullName: "The Fifth Book of Moses:  Called Deuteronomy",
  }),
  BibleBook.make({
    name: "Joshua",
    author: "shua",
    description: "The conquest and division of Canaan",
    firstChapter: 1,
    lastChapter: 24,
    fullName: "The Book of Joshua",
  }),
  BibleBook.make({
    name: "Judges",
    author: "known",
    description: "Israel's cycles of sin and deliverance",
    firstChapter: 1,
    lastChapter: 21,
    fullName: "The Book of Judges",
  }),
  BibleBook.make({
    name: "Ruth",
    author: "nown",
    description: "A story of loyalty and redemption",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Book of Ruth",
  }),
  BibleBook.make({
    name: "1 Samuel",
    author: "known",
    description: "The transition from judges to kings",
    firstChapter: 1,
    lastChapter: 31,
    fullName: "The First Book of Samuel",
  }),
  BibleBook.make({
    name: "2 Samuel",
    author: "known",
    description: "The reign of King David",
    firstChapter: 1,
    lastChapter: 24,
    fullName: "The Second Book of Samuel",
  }),
  BibleBook.make({
    name: "1 Kings",
    author: "known",
    description: "Solomon's reign and the divided kingdom",
    firstChapter: 1,
    lastChapter: 22,
    fullName: "The First Book of the Kings",
  }),
  BibleBook.make({
    name: "2 Kings",
    author: "known",
    description: "The decline and fall of Israel and Judah",
    firstChapter: 1,
    lastChapter: 25,
    fullName: "The Second Book of the Kings",
  }),
  BibleBook.make({
    name: "1 Chronicles",
    author: "ra",
    description: "A priestly history of David's reign",
    firstChapter: 1,
    lastChapter: 29,
    fullName: "The First Book of the Chronicles",
  }),
  BibleBook.make({
    name: "2 Chronicles",
    author: "ra",
    description: "A priestly history of Solomon to exile",
    firstChapter: 1,
    lastChapter: 36,
    fullName: "The Second Book of the Chronicles",
  }),
  BibleBook.make({
    name: "Ezra",
    author: "Ezra",
    description: "The return from exile and temple rebuilding",
    firstChapter: 1,
    lastChapter: 10,
    fullName: "",
  }),
  BibleBook.make({
    name: "Nehemiah",
    author: "Nehemiah",
    description: "Rebuilding Jerusalem's walls",
    firstChapter: 1,
    lastChapter: 13,
    fullName: "The Book of Nehemiah",
  }),
  BibleBook.make({
    name: "Esther",
    author: "Unknown",
    description: "God's providence in preserving His people",
    firstChapter: 1,
    lastChapter: 10,
    fullName: "The Book of Esther",
  }),
  BibleBook.make({
    name: "Job",
    author: "Unknown",
    description: "The problem of suffering and God's sovereignty",
    firstChapter: 1,
    lastChapter: 42,
    fullName: "The Book of Job",
  }),
  BibleBook.make({
    name: "Psalms",
    author: "Various",
    description: "Israel's hymnal and prayer book",
    firstChapter: 1,
    lastChapter: 150,
    fullName: "The Book of Psalms",
  }),
  BibleBook.make({
    name: "Proverbs",
    author: "Solomon and others",
    description: "Wisdom for daily living",
    firstChapter: 1,
    lastChapter: 31,
    fullName: "The Proverbs",
  }),
  BibleBook.make({
    name: "Ecclesiastes",
    author: "Solomon",
    description: "The search for meaning in life",
    firstChapter: 1,
    lastChapter: 12,
    fullName: "The Preacher",
  }),
  BibleBook.make({
    name: "Song of Solomon",
    author: "Solomon",
    description: "A celebration of love and marriage",
    firstChapter: 1,
    lastChapter: 8,
    fullName: "The Song of Solomon",
  }),
  BibleBook.make({
    name: "Isaiah",
    author: "Isaiah",
    description: "Prophecies of judgment and the coming Messiah",
    firstChapter: 1,
    lastChapter: 66,
    fullName: "The Book of the Prophet Isaiah",
  }),
  BibleBook.make({
    name: "Jeremiah",
    author: "Jeremiah",
    description: "Warnings of judgment and calls to repentance",
    firstChapter: 1,
    lastChapter: 52,
    fullName: "The Book of the Prophet Jeremiah",
  }),
  BibleBook.make({
    name: "Lamentations",
    author: "Jeremiah",
    description: "Mourning over Jerusalem's destruction",
    firstChapter: 1,
    lastChapter: 5,
    fullName: "The Lamentations of Jeremiah",
  }),
  BibleBook.make({
    name: "Ezekiel",
    author: "Ezekiel",
    description: "Visions of God's glory and restoration",
    firstChapter: 1,
    lastChapter: 48,
    fullName: "The Book of the Prophet Ezekiel",
  }),
  BibleBook.make({
    name: "Daniel",
    author: "Daniel",
    description: "Faithfulness in exile and prophetic visions",
    firstChapter: 1,
    lastChapter: 12,
    fullName: "The Book of Daniel",
  }),
  BibleBook.make({
    name: "Hosea",
    author: "Hosea",
    description: "God's faithful love despite Israel's unfaithfulness",
    firstChapter: 1,
    lastChapter: 14,
    fullName: "The Book of Hosea",
  }),
  BibleBook.make({
    name: "Joel",
    author: "Joel",
    description: "The Day of the Lord and spiritual renewal",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Book of Joel",
  }),
  BibleBook.make({
    name: "Amos",
    author: "Amos",
    description: "God's judgment on injustice",
    firstChapter: 1,
    lastChapter: 9,
  }),
  BibleBook.make({
    name: "Obadiah",
    author: "Obadiah",
    description: "Judgment on Edom",
    firstChapter: 1,
    lastChapter: 1,
    fullName: "The Book of Obadiah",
  }),
  BibleBook.make({
    name: "Jonah",
    author: "Jonah",
    description: "God's mercy extends to all nations",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Book of Jonah",
  }),
  BibleBook.make({
    name: "Micah",
    author: "Micah",
    description: "Justice, mercy, and the coming ruler",
    firstChapter: 1,
    lastChapter: 7,
    fullName: "The Book of Micah",
  }),
  BibleBook.make({
    name: "Nahum",
    author: "Nahum",
    description: "God's judgment on Nineveh",
    firstChapter: 1,
    lastChapter: 3,
  }),
  BibleBook.make({
    name: "Habakkuk",
    author: "Habakkuk",
    description: "Living by faith in difficult times",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Book of Habakkuk",
  }),
  BibleBook.make({
    name: "Zephaniah",
    author: "Zephaniah",
    description: "The Day of the Lord and restoration",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Book of Zephaniah",
  }),
  BibleBook.make({
    name: "Haggai",
    author: "Haggai",
    description: "Rebuilding the temple with right priorities",
    firstChapter: 1,
    lastChapter: 2,
    fullName: "Haggai",
  }),
  BibleBook.make({
    name: "Zechariah",
    author: "Zechariah",
    description: "Visions of restoration and the Messiah",
    firstChapter: 1,
    lastChapter: 14,
    fullName: "The Book of Zechariah",
  }),
  BibleBook.make({
    name: "Malachi",
    author: "Malachi",
    description: "A call to covenant faithfulness",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Book of Malachi",
  }),
  BibleBook.make({
    name: "Matthew",
    author: "atthew",
    description: "Jesus as the promised Messiah and King",
    firstChapter: 1,
    lastChapter: 28,
    fullName: "The Gospel According to Saint Matthew",
  }),
  BibleBook.make({
    name: "Mark",
    author: "ohn Mark",
    description: "Jesus as the suffering Servant",
    firstChapter: 1,
    lastChapter: 16,
    fullName: "The Gospel According to Saint Mark",
  }),
  BibleBook.make({
    name: "Luke",
    author: "uke",
    description: "Jesus as the Son of Man for all people",
    firstChapter: 1,
    lastChapter: 24,
    fullName: "The Gospel According to Saint Luke",
  }),
  BibleBook.make({
    name: "John",
    author: "ohn",
    description: "Jesus as the Son of God",
    firstChapter: 1,
    lastChapter: 21,
    fullName: "The Gospel According to Saint John",
  }),
  BibleBook.make({
    name: "Acts",
    author: "uke",
    description: "The birth and growth of the early church",
    firstChapter: 1,
    lastChapter: 28,
    fullName: "The Acts of the Apostles",
  }),
  BibleBook.make({
    name: "Romans",
    author: "aul",
    description: "The gospel of justification by faith",
    firstChapter: 1,
    lastChapter: 16,
    fullName: "The Epistle of Paul the Apostle to the Romans",
  }),
  BibleBook.make({
    name: "1 Corinthians",
    author: "aul",
    description: "Addressing problems in the Corinthian church",
    firstChapter: 1,
    lastChapter: 16,
    fullName: "The First Epistle of Paul the Apostle to the Corinthians",
  }),
  BibleBook.make({
    name: "2 Corinthians",
    author: "aul",
    description: "Paul's defense of his apostolic ministry",
    firstChapter: 1,
    lastChapter: 13,
    fullName: "The Second Epistle of Paul the Apostle to the Corinthians",
  }),
  BibleBook.make({
    name: "Galatians",
    author: "aul",
    description: "Freedom in Christ and justification by faith",
    firstChapter: 1,
    lastChapter: 6,
    fullName: "The Epistle of Paul the Apostle to the Galatians",
  }),
  BibleBook.make({
    name: "Ephesians",
    author: "aul",
    description: "The church as the body of Christ",
    firstChapter: 1,
    lastChapter: 6,
    fullName: "The Epistle of Paul the Apostle to the Ephesians",
  }),
  BibleBook.make({
    name: "Philippians",
    author: "aul",
    description: "Joy and unity in Christ",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Epistle of Paul the Apostle to the Philippians",
  }),
  BibleBook.make({
    name: "Colossians",
    author: "aul",
    description: "The supremacy of Christ",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Epistle of Paul the Apostle to the Colossians",
  }),
  BibleBook.make({
    name: "1 Thessalonians",
    author: "aul",
    description: "Living for Christ's return",
    firstChapter: 1,
    lastChapter: 5,
    fullName: "The First Epistle of Paul the Apostle to the Thessalonians",
  }),
  BibleBook.make({
    name: "2 Thessalonians",
    author: "aul",
    description: "Correcting misunderstandings about Christ's return",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Second Epistle of Paul the Apostle to the Thessalonians",
  }),
  BibleBook.make({
    name: "1 Timothy",
    author: "aul",
    description: "Instructions for church leadership",
    firstChapter: 1,
    lastChapter: 6,
    fullName: "The First Epistle of Paul the Apostle to Timothy",
  }),
  BibleBook.make({
    name: "2 Timothy",
    author: "aul",
    description: "Paul's final charge to Timothy",
    firstChapter: 1,
    lastChapter: 4,
    fullName: "The Second Epistle of Paul the Apostle to Timothy",
  }),
  BibleBook.make({
    name: "Titus",
    author: "aul",
    description: "Church order and sound doctrine",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Epistle of Paul the Apostle to Titus",
  }),
  BibleBook.make({
    name: "Philemon",
    author: "aul",
    description: "A personal appeal for Christian forgiveness",
    firstChapter: 1,
    lastChapter: 1,
    fullName: "The Epistle of Paul the Apostle to Philemon",
  }),
  BibleBook.make({
    name: "Hebrews",
    author: "nknown",
    description: "The superiority of Christ and the new covenant",
    firstChapter: 1,
    lastChapter: 13,
    fullName: "The Epistle of Paul the Apostle to the Hebrews",
  }),
  BibleBook.make({
    name: "James",
    author: "ames",
    description: "Practical Christian living and faith in action",
    firstChapter: 1,
    lastChapter: 5,
    fullName: "The General Epistle of James",
  }),
  BibleBook.make({
    name: "1 Peter",
    author: "eter",
    description: "Hope and holiness in suffering",
    firstChapter: 1,
    lastChapter: 5,
    fullName: "The First Epistle General of Peter",
  }),
  BibleBook.make({
    name: "2 Peter",
    author: "eter",
    description: "Warning against false teachers",
    firstChapter: 1,
    lastChapter: 3,
    fullName: "The Second General Epistle of Peter",
  }),
  BibleBook.make({
    name: "1 John",
    author: "ohn",
    description: "The assurance of eternal life and love",
    firstChapter: 1,
    lastChapter: 5,
    fullName: "The First Epistle General of John",
  }),
  BibleBook.make({
    name: "2 John",
    author: "ohn",
    description: "Walking in truth and love",
    firstChapter: 1,
    lastChapter: 1,
    fullName: "The Second Epistle General of John",
  }),
  BibleBook.make({
    name: "3 John",
    author: "ohn",
    description: "Hospitality and truth in the church",
    firstChapter: 1,
    lastChapter: 1,
    fullName: "The Third Epistle General of John",
  }),
  BibleBook.make({
    name: "Jude",
    author: "Jude",
    description: "Contending for the faith",
    firstChapter: 1,
    lastChapter: 1,
    fullName: "The General Epistle of Jude",
  }),
  BibleBook.make({
    name: "Revelation",
    author: "John",
    description: "The ultimate victory of Christ and His kingdom",
    firstChapter: 1,
    lastChapter: 22,
    fullName: "The Revelation of Saint John the Devine",
  }),
];
