import { BibleBook } from "../../entities/bible-book.entity";
import { Chapter } from "../../value-objects/chapter";

export const BIBLE_BOOKS: BibleBook[] = [
  BibleBook.make({
    name: "Genesis",
    author: "es",
    description: "The book of beginnings, creation, and the patriarchs",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 31 }),
      Chapter.make({ number: 2, numberOfVerses: 25 }),
      Chapter.make({ number: 3, numberOfVerses: 24 }),
      Chapter.make({ number: 4, numberOfVerses: 26 }),
      Chapter.make({ number: 5, numberOfVerses: 32 }),
      Chapter.make({ number: 6, numberOfVerses: 22 }),
      Chapter.make({ number: 7, numberOfVerses: 24 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 29 }),
      Chapter.make({ number: 10, numberOfVerses: 32 }),
      Chapter.make({ number: 11, numberOfVerses: 32 }),
      Chapter.make({ number: 12, numberOfVerses: 20 }),
      Chapter.make({ number: 13, numberOfVerses: 18 }),
      Chapter.make({ number: 14, numberOfVerses: 24 }),
      Chapter.make({ number: 15, numberOfVerses: 21 }),
      Chapter.make({ number: 16, numberOfVerses: 16 }),
      Chapter.make({ number: 17, numberOfVerses: 27 }),
      Chapter.make({ number: 18, numberOfVerses: 33 }),
      Chapter.make({ number: 19, numberOfVerses: 38 }),
      Chapter.make({ number: 20, numberOfVerses: 18 }),
      Chapter.make({ number: 21, numberOfVerses: 34 }),
      Chapter.make({ number: 22, numberOfVerses: 24 }),
      Chapter.make({ number: 23, numberOfVerses: 20 }),
      Chapter.make({ number: 24, numberOfVerses: 67 }),
      Chapter.make({ number: 25, numberOfVerses: 34 }),
      Chapter.make({ number: 26, numberOfVerses: 35 }),
      Chapter.make({ number: 27, numberOfVerses: 46 }),
      Chapter.make({ number: 28, numberOfVerses: 22 }),
      Chapter.make({ number: 29, numberOfVerses: 35 }),
      Chapter.make({ number: 30, numberOfVerses: 43 }),
      Chapter.make({ number: 31, numberOfVerses: 55 }),
      Chapter.make({ number: 32, numberOfVerses: 32 }),
      Chapter.make({ number: 33, numberOfVerses: 20 }),
      Chapter.make({ number: 34, numberOfVerses: 31 }),
      Chapter.make({ number: 35, numberOfVerses: 29 }),
      Chapter.make({ number: 36, numberOfVerses: 43 }),
      Chapter.make({ number: 37, numberOfVerses: 36 }),
      Chapter.make({ number: 38, numberOfVerses: 30 }),
      Chapter.make({ number: 39, numberOfVerses: 23 }),
      Chapter.make({ number: 40, numberOfVerses: 23 }),
      Chapter.make({ number: 41, numberOfVerses: 57 }),
      Chapter.make({ number: 42, numberOfVerses: 38 }),
      Chapter.make({ number: 43, numberOfVerses: 34 }),
      Chapter.make({ number: 44, numberOfVerses: 34 }),
      Chapter.make({ number: 45, numberOfVerses: 28 }),
      Chapter.make({ number: 46, numberOfVerses: 34 }),
      Chapter.make({ number: 47, numberOfVerses: 31 }),
      Chapter.make({ number: 48, numberOfVerses: 22 }),
      Chapter.make({ number: 49, numberOfVerses: 33 }),
      Chapter.make({ number: 50, numberOfVerses: 26 }),
    ],
    fullName: "The First Book of Moses:  Called Genesis",
  }),
  BibleBook.make({
    name: "Exodus",
    author: "es",
    description: "The deliverance of Israel from Egypt",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 22 }),
      Chapter.make({ number: 2, numberOfVerses: 25 }),
      Chapter.make({ number: 3, numberOfVerses: 22 }),
      Chapter.make({ number: 4, numberOfVerses: 31 }),
      Chapter.make({ number: 5, numberOfVerses: 23 }),
      Chapter.make({ number: 6, numberOfVerses: 30 }),
      Chapter.make({ number: 7, numberOfVerses: 25 }),
      Chapter.make({ number: 8, numberOfVerses: 32 }),
      Chapter.make({ number: 9, numberOfVerses: 35 }),
      Chapter.make({ number: 10, numberOfVerses: 29 }),
      Chapter.make({ number: 11, numberOfVerses: 10 }),
      Chapter.make({ number: 12, numberOfVerses: 51 }),
      Chapter.make({ number: 13, numberOfVerses: 22 }),
      Chapter.make({ number: 14, numberOfVerses: 31 }),
      Chapter.make({ number: 15, numberOfVerses: 27 }),
      Chapter.make({ number: 16, numberOfVerses: 36 }),
      Chapter.make({ number: 17, numberOfVerses: 16 }),
      Chapter.make({ number: 18, numberOfVerses: 27 }),
      Chapter.make({ number: 19, numberOfVerses: 25 }),
      Chapter.make({ number: 20, numberOfVerses: 26 }),
      Chapter.make({ number: 21, numberOfVerses: 36 }),
      Chapter.make({ number: 22, numberOfVerses: 31 }),
      Chapter.make({ number: 23, numberOfVerses: 33 }),
      Chapter.make({ number: 24, numberOfVerses: 18 }),
      Chapter.make({ number: 25, numberOfVerses: 40 }),
      Chapter.make({ number: 26, numberOfVerses: 37 }),
      Chapter.make({ number: 27, numberOfVerses: 21 }),
      Chapter.make({ number: 28, numberOfVerses: 43 }),
      Chapter.make({ number: 29, numberOfVerses: 46 }),
      Chapter.make({ number: 30, numberOfVerses: 38 }),
      Chapter.make({ number: 31, numberOfVerses: 18 }),
      Chapter.make({ number: 32, numberOfVerses: 35 }),
      Chapter.make({ number: 33, numberOfVerses: 23 }),
      Chapter.make({ number: 34, numberOfVerses: 35 }),
      Chapter.make({ number: 35, numberOfVerses: 35 }),
      Chapter.make({ number: 36, numberOfVerses: 38 }),
      Chapter.make({ number: 37, numberOfVerses: 29 }),
      Chapter.make({ number: 38, numberOfVerses: 31 }),
      Chapter.make({ number: 39, numberOfVerses: 43 }),
      Chapter.make({ number: 40, numberOfVerses: 38 }),
    ],
    fullName: "The Second Book of Moses:  Called Exodus",
  }),
  BibleBook.make({
    name: "Leviticus",
    author: "ses",
    description: "Laws and rituals for Israel's worship",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 17 }),
      Chapter.make({ number: 2, numberOfVerses: 16 }),
      Chapter.make({ number: 3, numberOfVerses: 17 }),
      Chapter.make({ number: 4, numberOfVerses: 35 }),
      Chapter.make({ number: 5, numberOfVerses: 19 }),
      Chapter.make({ number: 6, numberOfVerses: 30 }),
      Chapter.make({ number: 7, numberOfVerses: 38 }),
      Chapter.make({ number: 8, numberOfVerses: 36 }),
      Chapter.make({ number: 9, numberOfVerses: 24 }),
      Chapter.make({ number: 10, numberOfVerses: 20 }),
      Chapter.make({ number: 11, numberOfVerses: 47 }),
      Chapter.make({ number: 12, numberOfVerses: 8 }),
      Chapter.make({ number: 13, numberOfVerses: 59 }),
      Chapter.make({ number: 14, numberOfVerses: 57 }),
      Chapter.make({ number: 15, numberOfVerses: 33 }),
      Chapter.make({ number: 16, numberOfVerses: 34 }),
      Chapter.make({ number: 17, numberOfVerses: 16 }),
      Chapter.make({ number: 18, numberOfVerses: 30 }),
      Chapter.make({ number: 19, numberOfVerses: 37 }),
      Chapter.make({ number: 20, numberOfVerses: 27 }),
      Chapter.make({ number: 21, numberOfVerses: 24 }),
      Chapter.make({ number: 22, numberOfVerses: 33 }),
      Chapter.make({ number: 23, numberOfVerses: 44 }),
      Chapter.make({ number: 24, numberOfVerses: 23 }),
      Chapter.make({ number: 25, numberOfVerses: 55 }),
      Chapter.make({ number: 26, numberOfVerses: 46 }),
      Chapter.make({ number: 27, numberOfVerses: 34 }),
    ],
    fullName: "The Third Book of Moses:  Called Leviticus",
  }),
  BibleBook.make({
    name: "Numbers",
    author: "ses",
    description: "Israel's wandering in the wilderness",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 54 }),
      Chapter.make({ number: 2, numberOfVerses: 34 }),
      Chapter.make({ number: 3, numberOfVerses: 51 }),
      Chapter.make({ number: 4, numberOfVerses: 49 }),
      Chapter.make({ number: 5, numberOfVerses: 31 }),
      Chapter.make({ number: 6, numberOfVerses: 27 }),
      Chapter.make({ number: 7, numberOfVerses: 89 }),
      Chapter.make({ number: 8, numberOfVerses: 26 }),
      Chapter.make({ number: 9, numberOfVerses: 23 }),
      Chapter.make({ number: 10, numberOfVerses: 36 }),
      Chapter.make({ number: 11, numberOfVerses: 35 }),
      Chapter.make({ number: 12, numberOfVerses: 16 }),
      Chapter.make({ number: 13, numberOfVerses: 33 }),
      Chapter.make({ number: 14, numberOfVerses: 45 }),
      Chapter.make({ number: 15, numberOfVerses: 41 }),
      Chapter.make({ number: 16, numberOfVerses: 50 }),
      Chapter.make({ number: 17, numberOfVerses: 13 }),
      Chapter.make({ number: 18, numberOfVerses: 32 }),
      Chapter.make({ number: 19, numberOfVerses: 22 }),
      Chapter.make({ number: 20, numberOfVerses: 29 }),
      Chapter.make({ number: 21, numberOfVerses: 35 }),
      Chapter.make({ number: 22, numberOfVerses: 41 }),
      Chapter.make({ number: 23, numberOfVerses: 30 }),
      Chapter.make({ number: 24, numberOfVerses: 25 }),
      Chapter.make({ number: 25, numberOfVerses: 18 }),
      Chapter.make({ number: 26, numberOfVerses: 65 }),
      Chapter.make({ number: 27, numberOfVerses: 23 }),
      Chapter.make({ number: 28, numberOfVerses: 31 }),
      Chapter.make({ number: 29, numberOfVerses: 40 }),
      Chapter.make({ number: 30, numberOfVerses: 16 }),
      Chapter.make({ number: 31, numberOfVerses: 54 }),
      Chapter.make({ number: 32, numberOfVerses: 42 }),
      Chapter.make({ number: 33, numberOfVerses: 56 }),
      Chapter.make({ number: 34, numberOfVerses: 29 }),
      Chapter.make({ number: 35, numberOfVerses: 34 }),
      Chapter.make({ number: 36, numberOfVerses: 13 }),
    ],
    fullName: "The Fourth Book of Moses:  Called Numbers",
  }),
  BibleBook.make({
    name: "Deuteronomy",
    author: "ses",
    description: "Moses' final words to Israel",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 46 }),
      Chapter.make({ number: 2, numberOfVerses: 37 }),
      Chapter.make({ number: 3, numberOfVerses: 29 }),
      Chapter.make({ number: 4, numberOfVerses: 49 }),
      Chapter.make({ number: 5, numberOfVerses: 33 }),
      Chapter.make({ number: 6, numberOfVerses: 25 }),
      Chapter.make({ number: 7, numberOfVerses: 26 }),
      Chapter.make({ number: 8, numberOfVerses: 20 }),
      Chapter.make({ number: 9, numberOfVerses: 29 }),
      Chapter.make({ number: 10, numberOfVerses: 22 }),
      Chapter.make({ number: 11, numberOfVerses: 32 }),
      Chapter.make({ number: 12, numberOfVerses: 32 }),
      Chapter.make({ number: 13, numberOfVerses: 18 }),
      Chapter.make({ number: 14, numberOfVerses: 29 }),
      Chapter.make({ number: 15, numberOfVerses: 23 }),
      Chapter.make({ number: 16, numberOfVerses: 22 }),
      Chapter.make({ number: 17, numberOfVerses: 20 }),
      Chapter.make({ number: 18, numberOfVerses: 22 }),
      Chapter.make({ number: 19, numberOfVerses: 21 }),
      Chapter.make({ number: 20, numberOfVerses: 20 }),
      Chapter.make({ number: 21, numberOfVerses: 23 }),
      Chapter.make({ number: 22, numberOfVerses: 30 }),
      Chapter.make({ number: 23, numberOfVerses: 25 }),
      Chapter.make({ number: 24, numberOfVerses: 22 }),
      Chapter.make({ number: 25, numberOfVerses: 19 }),
      Chapter.make({ number: 26, numberOfVerses: 19 }),
      Chapter.make({ number: 27, numberOfVerses: 26 }),
      Chapter.make({ number: 28, numberOfVerses: 68 }),
      Chapter.make({ number: 29, numberOfVerses: 29 }),
      Chapter.make({ number: 30, numberOfVerses: 20 }),
      Chapter.make({ number: 31, numberOfVerses: 30 }),
      Chapter.make({ number: 32, numberOfVerses: 52 }),
      Chapter.make({ number: 33, numberOfVerses: 29 }),
      Chapter.make({ number: 34, numberOfVerses: 12 }),
    ],
    fullName: "The Fifth Book of Moses:  Called Deuteronomy",
  }),
  BibleBook.make({
    name: "Joshua",
    author: "shua",
    description: "The conquest and division of Canaan",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 18 }),
      Chapter.make({ number: 2, numberOfVerses: 24 }),
      Chapter.make({ number: 3, numberOfVerses: 17 }),
      Chapter.make({ number: 4, numberOfVerses: 24 }),
      Chapter.make({ number: 5, numberOfVerses: 15 }),
      Chapter.make({ number: 6, numberOfVerses: 27 }),
      Chapter.make({ number: 7, numberOfVerses: 26 }),
      Chapter.make({ number: 8, numberOfVerses: 35 }),
      Chapter.make({ number: 9, numberOfVerses: 27 }),
      Chapter.make({ number: 10, numberOfVerses: 43 }),
      Chapter.make({ number: 11, numberOfVerses: 23 }),
      Chapter.make({ number: 12, numberOfVerses: 24 }),
      Chapter.make({ number: 13, numberOfVerses: 33 }),
      Chapter.make({ number: 14, numberOfVerses: 15 }),
      Chapter.make({ number: 15, numberOfVerses: 63 }),
      Chapter.make({ number: 16, numberOfVerses: 10 }),
      Chapter.make({ number: 17, numberOfVerses: 18 }),
      Chapter.make({ number: 18, numberOfVerses: 28 }),
      Chapter.make({ number: 19, numberOfVerses: 51 }),
      Chapter.make({ number: 20, numberOfVerses: 9 }),
      Chapter.make({ number: 21, numberOfVerses: 45 }),
      Chapter.make({ number: 22, numberOfVerses: 34 }),
      Chapter.make({ number: 23, numberOfVerses: 16 }),
      Chapter.make({ number: 24, numberOfVerses: 33 }),
    ],
    fullName: "The Book of Joshua",
  }),
  BibleBook.make({
    name: "Judges",
    author: "known",
    description: "Israel's cycles of sin and deliverance",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 36 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 31 }),
      Chapter.make({ number: 4, numberOfVerses: 24 }),
      Chapter.make({ number: 5, numberOfVerses: 31 }),
      Chapter.make({ number: 6, numberOfVerses: 40 }),
      Chapter.make({ number: 7, numberOfVerses: 25 }),
      Chapter.make({ number: 8, numberOfVerses: 35 }),
      Chapter.make({ number: 9, numberOfVerses: 57 }),
      Chapter.make({ number: 10, numberOfVerses: 18 }),
      Chapter.make({ number: 11, numberOfVerses: 40 }),
      Chapter.make({ number: 12, numberOfVerses: 15 }),
      Chapter.make({ number: 13, numberOfVerses: 25 }),
      Chapter.make({ number: 14, numberOfVerses: 20 }),
      Chapter.make({ number: 15, numberOfVerses: 20 }),
      Chapter.make({ number: 16, numberOfVerses: 31 }),
      Chapter.make({ number: 17, numberOfVerses: 13 }),
      Chapter.make({ number: 18, numberOfVerses: 31 }),
      Chapter.make({ number: 19, numberOfVerses: 30 }),
      Chapter.make({ number: 20, numberOfVerses: 48 }),
      Chapter.make({ number: 21, numberOfVerses: 25 }),
    ],
    fullName: "The Book of Judges",
  }),
  BibleBook.make({
    name: "Ruth",
    author: "nown",
    description: "A story of loyalty and redemption",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 22 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
    ],
    fullName: "The Book of Ruth",
  }),
  BibleBook.make({
    name: "1 Samuel",
    author: "known",
    description: "The transition from judges to kings",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 28 }),
      Chapter.make({ number: 2, numberOfVerses: 36 }),
      Chapter.make({ number: 3, numberOfVerses: 21 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
      Chapter.make({ number: 5, numberOfVerses: 12 }),
      Chapter.make({ number: 6, numberOfVerses: 21 }),
      Chapter.make({ number: 7, numberOfVerses: 17 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 27 }),
      Chapter.make({ number: 10, numberOfVerses: 27 }),
      Chapter.make({ number: 11, numberOfVerses: 15 }),
      Chapter.make({ number: 12, numberOfVerses: 25 }),
      Chapter.make({ number: 13, numberOfVerses: 23 }),
      Chapter.make({ number: 14, numberOfVerses: 52 }),
      Chapter.make({ number: 15, numberOfVerses: 35 }),
      Chapter.make({ number: 16, numberOfVerses: 23 }),
      Chapter.make({ number: 17, numberOfVerses: 58 }),
      Chapter.make({ number: 18, numberOfVerses: 30 }),
      Chapter.make({ number: 19, numberOfVerses: 24 }),
      Chapter.make({ number: 20, numberOfVerses: 42 }),
      Chapter.make({ number: 21, numberOfVerses: 15 }),
      Chapter.make({ number: 22, numberOfVerses: 23 }),
      Chapter.make({ number: 23, numberOfVerses: 29 }),
      Chapter.make({ number: 24, numberOfVerses: 22 }),
      Chapter.make({ number: 25, numberOfVerses: 44 }),
      Chapter.make({ number: 26, numberOfVerses: 25 }),
      Chapter.make({ number: 27, numberOfVerses: 12 }),
      Chapter.make({ number: 28, numberOfVerses: 25 }),
      Chapter.make({ number: 29, numberOfVerses: 11 }),
      Chapter.make({ number: 30, numberOfVerses: 31 }),
      Chapter.make({ number: 31, numberOfVerses: 13 }),
    ],
    fullName: "The First Book of Samuel",
  }),
  BibleBook.make({
    name: "2 Samuel",
    author: "known",
    description: "The reign of King David",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 27 }),
      Chapter.make({ number: 2, numberOfVerses: 32 }),
      Chapter.make({ number: 3, numberOfVerses: 39 }),
      Chapter.make({ number: 4, numberOfVerses: 12 }),
      Chapter.make({ number: 5, numberOfVerses: 25 }),
      Chapter.make({ number: 6, numberOfVerses: 23 }),
      Chapter.make({ number: 7, numberOfVerses: 29 }),
      Chapter.make({ number: 8, numberOfVerses: 18 }),
      Chapter.make({ number: 9, numberOfVerses: 13 }),
      Chapter.make({ number: 10, numberOfVerses: 19 }),
      Chapter.make({ number: 11, numberOfVerses: 27 }),
      Chapter.make({ number: 12, numberOfVerses: 31 }),
      Chapter.make({ number: 13, numberOfVerses: 39 }),
      Chapter.make({ number: 14, numberOfVerses: 33 }),
      Chapter.make({ number: 15, numberOfVerses: 37 }),
      Chapter.make({ number: 16, numberOfVerses: 23 }),
      Chapter.make({ number: 17, numberOfVerses: 29 }),
      Chapter.make({ number: 18, numberOfVerses: 33 }),
      Chapter.make({ number: 19, numberOfVerses: 43 }),
      Chapter.make({ number: 20, numberOfVerses: 26 }),
      Chapter.make({ number: 21, numberOfVerses: 22 }),
      Chapter.make({ number: 22, numberOfVerses: 51 }),
      Chapter.make({ number: 23, numberOfVerses: 39 }),
      Chapter.make({ number: 24, numberOfVerses: 25 }),
    ],
    fullName: "The Second Book of Samuel",
  }),
  BibleBook.make({
    name: "1 Kings",
    author: "known",
    description: "Solomon's reign and the divided kingdom",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 28 }),
      Chapter.make({ number: 2, numberOfVerses: 36 }),
      Chapter.make({ number: 3, numberOfVerses: 21 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
      Chapter.make({ number: 5, numberOfVerses: 12 }),
      Chapter.make({ number: 6, numberOfVerses: 21 }),
      Chapter.make({ number: 7, numberOfVerses: 17 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 27 }),
      Chapter.make({ number: 10, numberOfVerses: 27 }),
      Chapter.make({ number: 11, numberOfVerses: 15 }),
      Chapter.make({ number: 12, numberOfVerses: 25 }),
      Chapter.make({ number: 13, numberOfVerses: 23 }),
      Chapter.make({ number: 14, numberOfVerses: 52 }),
      Chapter.make({ number: 15, numberOfVerses: 35 }),
      Chapter.make({ number: 16, numberOfVerses: 23 }),
      Chapter.make({ number: 17, numberOfVerses: 58 }),
      Chapter.make({ number: 18, numberOfVerses: 30 }),
      Chapter.make({ number: 19, numberOfVerses: 24 }),
      Chapter.make({ number: 20, numberOfVerses: 42 }),
      Chapter.make({ number: 21, numberOfVerses: 15 }),
      Chapter.make({ number: 22, numberOfVerses: 23 }),
      Chapter.make({ number: 23, numberOfVerses: 29 }),
      Chapter.make({ number: 24, numberOfVerses: 22 }),
      Chapter.make({ number: 25, numberOfVerses: 44 }),
      Chapter.make({ number: 26, numberOfVerses: 25 }),
      Chapter.make({ number: 27, numberOfVerses: 12 }),
      Chapter.make({ number: 28, numberOfVerses: 25 }),
      Chapter.make({ number: 29, numberOfVerses: 11 }),
      Chapter.make({ number: 30, numberOfVerses: 31 }),
      Chapter.make({ number: 31, numberOfVerses: 13 }),
    ],
    fullName: "The First Book of the Kings",
  }),
  BibleBook.make({
    name: "2 Kings",
    author: "known",
    description: "The decline and fall of Israel and Judah",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 53 }),
      Chapter.make({ number: 2, numberOfVerses: 46 }),
      Chapter.make({ number: 3, numberOfVerses: 39 }),
      Chapter.make({ number: 4, numberOfVerses: 44 }),
      Chapter.make({ number: 5, numberOfVerses: 27 }),
      Chapter.make({ number: 6, numberOfVerses: 38 }),
      Chapter.make({ number: 7, numberOfVerses: 51 }),
      Chapter.make({ number: 8, numberOfVerses: 66 }),
      Chapter.make({ number: 9, numberOfVerses: 37 }),
      Chapter.make({ number: 10, numberOfVerses: 36 }),
      Chapter.make({ number: 11, numberOfVerses: 43 }),
      Chapter.make({ number: 12, numberOfVerses: 33 }),
      Chapter.make({ number: 13, numberOfVerses: 39 }),
      Chapter.make({ number: 14, numberOfVerses: 33 }),
      Chapter.make({ number: 15, numberOfVerses: 38 }),
      Chapter.make({ number: 16, numberOfVerses: 34 }),
      Chapter.make({ number: 17, numberOfVerses: 41 }),
      Chapter.make({ number: 18, numberOfVerses: 46 }),
      Chapter.make({ number: 19, numberOfVerses: 43 }),
      Chapter.make({ number: 20, numberOfVerses: 43 }),
      Chapter.make({ number: 21, numberOfVerses: 29 }),
      Chapter.make({ number: 22, numberOfVerses: 53 }),
      Chapter.make({ number: 23, numberOfVerses: 39 }),
      Chapter.make({ number: 24, numberOfVerses: 25 }),
      Chapter.make({ number: 25, numberOfVerses: 30 }),
    ],
    fullName: "The Second Book of the Kings",
  }),
  BibleBook.make({
    name: "1 Chronicles",
    author: "ra",
    description: "A priestly history of David's reign",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 54 }),
      Chapter.make({ number: 2, numberOfVerses: 55 }),
      Chapter.make({ number: 3, numberOfVerses: 24 }),
      Chapter.make({ number: 4, numberOfVerses: 43 }),
      Chapter.make({ number: 5, numberOfVerses: 26 }),
      Chapter.make({ number: 6, numberOfVerses: 81 }),
      Chapter.make({ number: 7, numberOfVerses: 40 }),
      Chapter.make({ number: 8, numberOfVerses: 40 }),
      Chapter.make({ number: 9, numberOfVerses: 44 }),
      Chapter.make({ number: 10, numberOfVerses: 14 }),
      Chapter.make({ number: 11, numberOfVerses: 47 }),
      Chapter.make({ number: 12, numberOfVerses: 40 }),
      Chapter.make({ number: 13, numberOfVerses: 14 }),
      Chapter.make({ number: 14, numberOfVerses: 17 }),
      Chapter.make({ number: 15, numberOfVerses: 29 }),
      Chapter.make({ number: 16, numberOfVerses: 43 }),
      Chapter.make({ number: 17, numberOfVerses: 27 }),
      Chapter.make({ number: 18, numberOfVerses: 17 }),
      Chapter.make({ number: 19, numberOfVerses: 19 }),
      Chapter.make({ number: 20, numberOfVerses: 8 }),
      Chapter.make({ number: 21, numberOfVerses: 30 }),
      Chapter.make({ number: 22, numberOfVerses: 19 }),
      Chapter.make({ number: 23, numberOfVerses: 32 }),
      Chapter.make({ number: 24, numberOfVerses: 31 }),
      Chapter.make({ number: 25, numberOfVerses: 31 }),
      Chapter.make({ number: 26, numberOfVerses: 32 }),
      Chapter.make({ number: 27, numberOfVerses: 34 }),
      Chapter.make({ number: 28, numberOfVerses: 21 }),
      Chapter.make({ number: 29, numberOfVerses: 30 }),
    ],
    fullName: "The First Book of the Chronicles",
  }),
  BibleBook.make({
    name: "2 Chronicles",
    author: "ra",
    description: "A priestly history of Solomon to exile",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 17 }),
      Chapter.make({ number: 2, numberOfVerses: 18 }),
      Chapter.make({ number: 3, numberOfVerses: 17 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
      Chapter.make({ number: 5, numberOfVerses: 14 }),
      Chapter.make({ number: 6, numberOfVerses: 42 }),
      Chapter.make({ number: 7, numberOfVerses: 22 }),
      Chapter.make({ number: 8, numberOfVerses: 18 }),
      Chapter.make({ number: 9, numberOfVerses: 31 }),
      Chapter.make({ number: 10, numberOfVerses: 19 }),
      Chapter.make({ number: 11, numberOfVerses: 23 }),
      Chapter.make({ number: 12, numberOfVerses: 16 }),
      Chapter.make({ number: 13, numberOfVerses: 22 }),
      Chapter.make({ number: 14, numberOfVerses: 15 }),
      Chapter.make({ number: 15, numberOfVerses: 19 }),
      Chapter.make({ number: 16, numberOfVerses: 14 }),
      Chapter.make({ number: 17, numberOfVerses: 19 }),
      Chapter.make({ number: 18, numberOfVerses: 34 }),
      Chapter.make({ number: 19, numberOfVerses: 11 }),
      Chapter.make({ number: 20, numberOfVerses: 37 }),
      Chapter.make({ number: 21, numberOfVerses: 20 }),
      Chapter.make({ number: 22, numberOfVerses: 12 }),
      Chapter.make({ number: 23, numberOfVerses: 21 }),
      Chapter.make({ number: 24, numberOfVerses: 27 }),
      Chapter.make({ number: 25, numberOfVerses: 28 }),
      Chapter.make({ number: 26, numberOfVerses: 23 }),
      Chapter.make({ number: 27, numberOfVerses: 9 }),
      Chapter.make({ number: 28, numberOfVerses: 27 }),
      Chapter.make({ number: 29, numberOfVerses: 36 }),
      Chapter.make({ number: 30, numberOfVerses: 27 }),
      Chapter.make({ number: 31, numberOfVerses: 21 }),
      Chapter.make({ number: 32, numberOfVerses: 33 }),
      Chapter.make({ number: 33, numberOfVerses: 25 }),
      Chapter.make({ number: 34, numberOfVerses: 33 }),
      Chapter.make({ number: 35, numberOfVerses: 27 }),
      Chapter.make({ number: 36, numberOfVerses: 23 }),
    ],
    fullName: "The Second Book of the Chronicles",
  }),
  BibleBook.make({
    name: "Ezra",
    author: "Ezra",
    description: "The return from exile and temple rebuilding",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 11 }),
      Chapter.make({ number: 2, numberOfVerses: 70 }),
      Chapter.make({ number: 3, numberOfVerses: 13 }),
      Chapter.make({ number: 4, numberOfVerses: 24 }),
      Chapter.make({ number: 5, numberOfVerses: 17 }),
      Chapter.make({ number: 6, numberOfVerses: 22 }),
      Chapter.make({ number: 7, numberOfVerses: 28 }),
      Chapter.make({ number: 8, numberOfVerses: 36 }),
      Chapter.make({ number: 9, numberOfVerses: 15 }),
      Chapter.make({ number: 10, numberOfVerses: 44 }),
    ],
    fullName: "Ezra",
  }),
  BibleBook.make({
    name: "Nehemiah",
    author: "Nehemiah",
    description: "Rebuilding Jerusalem's walls",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 11 }),
      Chapter.make({ number: 2, numberOfVerses: 20 }),
      Chapter.make({ number: 3, numberOfVerses: 32 }),
      Chapter.make({ number: 4, numberOfVerses: 23 }),
      Chapter.make({ number: 5, numberOfVerses: 19 }),
      Chapter.make({ number: 6, numberOfVerses: 19 }),
      Chapter.make({ number: 7, numberOfVerses: 73 }),
      Chapter.make({ number: 8, numberOfVerses: 18 }),
      Chapter.make({ number: 9, numberOfVerses: 38 }),
      Chapter.make({ number: 10, numberOfVerses: 39 }),
      Chapter.make({ number: 11, numberOfVerses: 36 }),
      Chapter.make({ number: 12, numberOfVerses: 47 }),
      Chapter.make({ number: 13, numberOfVerses: 31 }),
    ],
    fullName: "The Book of Nehemiah",
  }),
  BibleBook.make({
    name: "Esther",
    author: "Unknown",
    description: "God's providence in preserving His people",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 22 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 15 }),
      Chapter.make({ number: 4, numberOfVerses: 17 }),
      Chapter.make({ number: 5, numberOfVerses: 14 }),
      Chapter.make({ number: 6, numberOfVerses: 14 }),
      Chapter.make({ number: 7, numberOfVerses: 10 }),
      Chapter.make({ number: 8, numberOfVerses: 17 }),
      Chapter.make({ number: 9, numberOfVerses: 32 }),
      Chapter.make({ number: 10, numberOfVerses: 3 }),
    ],
    fullName: "The Book of Esther",
  }),
  BibleBook.make({
    name: "Job",
    author: "Unknown",
    description: "The problem of suffering and God's sovereignty",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 22 }),
      Chapter.make({ number: 2, numberOfVerses: 13 }),
      Chapter.make({ number: 3, numberOfVerses: 26 }),
      Chapter.make({ number: 4, numberOfVerses: 21 }),
      Chapter.make({ number: 5, numberOfVerses: 27 }),
      Chapter.make({ number: 6, numberOfVerses: 30 }),
      Chapter.make({ number: 7, numberOfVerses: 21 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 35 }),
      Chapter.make({ number: 10, numberOfVerses: 22 }),
      Chapter.make({ number: 11, numberOfVerses: 20 }),
      Chapter.make({ number: 12, numberOfVerses: 25 }),
      Chapter.make({ number: 13, numberOfVerses: 28 }),
      Chapter.make({ number: 14, numberOfVerses: 22 }),
      Chapter.make({ number: 15, numberOfVerses: 35 }),
      Chapter.make({ number: 16, numberOfVerses: 22 }),
      Chapter.make({ number: 17, numberOfVerses: 16 }),
      Chapter.make({ number: 18, numberOfVerses: 21 }),
      Chapter.make({ number: 19, numberOfVerses: 29 }),
      Chapter.make({ number: 20, numberOfVerses: 29 }),
      Chapter.make({ number: 21, numberOfVerses: 34 }),
      Chapter.make({ number: 22, numberOfVerses: 30 }),
      Chapter.make({ number: 23, numberOfVerses: 17 }),
      Chapter.make({ number: 24, numberOfVerses: 25 }),
      Chapter.make({ number: 25, numberOfVerses: 6 }),
      Chapter.make({ number: 26, numberOfVerses: 14 }),
      Chapter.make({ number: 27, numberOfVerses: 23 }),
      Chapter.make({ number: 28, numberOfVerses: 28 }),
      Chapter.make({ number: 29, numberOfVerses: 25 }),
      Chapter.make({ number: 30, numberOfVerses: 31 }),
      Chapter.make({ number: 31, numberOfVerses: 40 }),
      Chapter.make({ number: 32, numberOfVerses: 22 }),
      Chapter.make({ number: 33, numberOfVerses: 33 }),
      Chapter.make({ number: 34, numberOfVerses: 37 }),
      Chapter.make({ number: 35, numberOfVerses: 16 }),
      Chapter.make({ number: 36, numberOfVerses: 33 }),
      Chapter.make({ number: 37, numberOfVerses: 24 }),
      Chapter.make({ number: 38, numberOfVerses: 41 }),
      Chapter.make({ number: 39, numberOfVerses: 30 }),
      Chapter.make({ number: 40, numberOfVerses: 24 }),
      Chapter.make({ number: 41, numberOfVerses: 34 }),
      Chapter.make({ number: 42, numberOfVerses: 17 }),
    ],
    fullName: "The Book of Job",
  }),
  BibleBook.make({
    name: "Psalms",
    author: "Various",
    description: "Israel's hymnal and prayer book",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 6 }),
      Chapter.make({ number: 2, numberOfVerses: 12 }),
      Chapter.make({ number: 3, numberOfVerses: 8 }),
      Chapter.make({ number: 4, numberOfVerses: 8 }),
      Chapter.make({ number: 5, numberOfVerses: 12 }),
      Chapter.make({ number: 6, numberOfVerses: 10 }),
      Chapter.make({ number: 7, numberOfVerses: 17 }),
      Chapter.make({ number: 8, numberOfVerses: 9 }),
      Chapter.make({ number: 9, numberOfVerses: 20 }),
      Chapter.make({ number: 10, numberOfVerses: 18 }),
      Chapter.make({ number: 11, numberOfVerses: 7 }),
      Chapter.make({ number: 12, numberOfVerses: 8 }),
      Chapter.make({ number: 13, numberOfVerses: 6 }),
      Chapter.make({ number: 14, numberOfVerses: 7 }),
      Chapter.make({ number: 15, numberOfVerses: 5 }),
      Chapter.make({ number: 16, numberOfVerses: 11 }),
      Chapter.make({ number: 17, numberOfVerses: 15 }),
      Chapter.make({ number: 18, numberOfVerses: 50 }),
      Chapter.make({ number: 19, numberOfVerses: 14 }),
      Chapter.make({ number: 20, numberOfVerses: 9 }),
      Chapter.make({ number: 21, numberOfVerses: 13 }),
      Chapter.make({ number: 22, numberOfVerses: 31 }),
      Chapter.make({ number: 23, numberOfVerses: 6 }),
      Chapter.make({ number: 24, numberOfVerses: 10 }),
      Chapter.make({ number: 25, numberOfVerses: 22 }),
      Chapter.make({ number: 26, numberOfVerses: 12 }),
      Chapter.make({ number: 27, numberOfVerses: 14 }),
      Chapter.make({ number: 28, numberOfVerses: 9 }),
      Chapter.make({ number: 29, numberOfVerses: 11 }),
      Chapter.make({ number: 30, numberOfVerses: 12 }),
      Chapter.make({ number: 31, numberOfVerses: 24 }),
      Chapter.make({ number: 32, numberOfVerses: 11 }),
      Chapter.make({ number: 33, numberOfVerses: 22 }),
      Chapter.make({ number: 34, numberOfVerses: 22 }),
      Chapter.make({ number: 35, numberOfVerses: 28 }),
      Chapter.make({ number: 36, numberOfVerses: 12 }),
      Chapter.make({ number: 37, numberOfVerses: 40 }),
      Chapter.make({ number: 38, numberOfVerses: 22 }),
      Chapter.make({ number: 39, numberOfVerses: 13 }),
      Chapter.make({ number: 40, numberOfVerses: 17 }),
      Chapter.make({ number: 41, numberOfVerses: 13 }),
      Chapter.make({ number: 42, numberOfVerses: 11 }),
      Chapter.make({ number: 43, numberOfVerses: 5 }),
      Chapter.make({ number: 44, numberOfVerses: 26 }),
      Chapter.make({ number: 45, numberOfVerses: 17 }),
      Chapter.make({ number: 46, numberOfVerses: 11 }),
      Chapter.make({ number: 47, numberOfVerses: 9 }),
      Chapter.make({ number: 48, numberOfVerses: 14 }),
      Chapter.make({ number: 49, numberOfVerses: 20 }),
      Chapter.make({ number: 50, numberOfVerses: 23 }),
      Chapter.make({ number: 51, numberOfVerses: 19 }),
      Chapter.make({ number: 52, numberOfVerses: 9 }),
      Chapter.make({ number: 53, numberOfVerses: 6 }),
      Chapter.make({ number: 54, numberOfVerses: 7 }),
      Chapter.make({ number: 55, numberOfVerses: 23 }),
      Chapter.make({ number: 56, numberOfVerses: 13 }),
      Chapter.make({ number: 57, numberOfVerses: 11 }),
      Chapter.make({ number: 58, numberOfVerses: 11 }),
      Chapter.make({ number: 59, numberOfVerses: 17 }),
      Chapter.make({ number: 60, numberOfVerses: 12 }),
      Chapter.make({ number: 61, numberOfVerses: 8 }),
      Chapter.make({ number: 62, numberOfVerses: 12 }),
      Chapter.make({ number: 63, numberOfVerses: 11 }),
      Chapter.make({ number: 64, numberOfVerses: 10 }),
      Chapter.make({ number: 65, numberOfVerses: 13 }),
      Chapter.make({ number: 66, numberOfVerses: 20 }),
      Chapter.make({ number: 67, numberOfVerses: 7 }),
      Chapter.make({ number: 68, numberOfVerses: 35 }),
      Chapter.make({ number: 69, numberOfVerses: 36 }),
      Chapter.make({ number: 70, numberOfVerses: 5 }),
      Chapter.make({ number: 71, numberOfVerses: 24 }),
      Chapter.make({ number: 72, numberOfVerses: 20 }),
      Chapter.make({ number: 73, numberOfVerses: 28 }),
      Chapter.make({ number: 74, numberOfVerses: 23 }),
      Chapter.make({ number: 75, numberOfVerses: 10 }),
      Chapter.make({ number: 76, numberOfVerses: 12 }),
      Chapter.make({ number: 77, numberOfVerses: 20 }),
      Chapter.make({ number: 78, numberOfVerses: 72 }),
      Chapter.make({ number: 79, numberOfVerses: 13 }),
      Chapter.make({ number: 80, numberOfVerses: 19 }),
      Chapter.make({ number: 81, numberOfVerses: 16 }),
      Chapter.make({ number: 82, numberOfVerses: 8 }),
      Chapter.make({ number: 83, numberOfVerses: 18 }),
      Chapter.make({ number: 84, numberOfVerses: 12 }),
      Chapter.make({ number: 85, numberOfVerses: 13 }),
      Chapter.make({ number: 86, numberOfVerses: 17 }),
      Chapter.make({ number: 87, numberOfVerses: 7 }),
      Chapter.make({ number: 88, numberOfVerses: 18 }),
      Chapter.make({ number: 89, numberOfVerses: 52 }),
      Chapter.make({ number: 90, numberOfVerses: 17 }),
      Chapter.make({ number: 91, numberOfVerses: 16 }),
      Chapter.make({ number: 92, numberOfVerses: 15 }),
      Chapter.make({ number: 93, numberOfVerses: 5 }),
      Chapter.make({ number: 94, numberOfVerses: 23 }),
      Chapter.make({ number: 95, numberOfVerses: 11 }),
      Chapter.make({ number: 96, numberOfVerses: 13 }),
      Chapter.make({ number: 97, numberOfVerses: 12 }),
      Chapter.make({ number: 98, numberOfVerses: 9 }),
      Chapter.make({ number: 99, numberOfVerses: 9 }),
      Chapter.make({ number: 100, numberOfVerses: 5 }),
      Chapter.make({ number: 101, numberOfVerses: 8 }),
      Chapter.make({ number: 102, numberOfVerses: 28 }),
      Chapter.make({ number: 103, numberOfVerses: 22 }),
      Chapter.make({ number: 104, numberOfVerses: 35 }),
      Chapter.make({ number: 105, numberOfVerses: 45 }),
      Chapter.make({ number: 106, numberOfVerses: 48 }),
      Chapter.make({ number: 107, numberOfVerses: 43 }),
      Chapter.make({ number: 108, numberOfVerses: 13 }),
      Chapter.make({ number: 109, numberOfVerses: 31 }),
      Chapter.make({ number: 110, numberOfVerses: 7 }),
      Chapter.make({ number: 111, numberOfVerses: 10 }),
      Chapter.make({ number: 112, numberOfVerses: 10 }),
      Chapter.make({ number: 113, numberOfVerses: 9 }),
      Chapter.make({ number: 114, numberOfVerses: 8 }),
      Chapter.make({ number: 115, numberOfVerses: 18 }),
      Chapter.make({ number: 116, numberOfVerses: 19 }),
      Chapter.make({ number: 117, numberOfVerses: 2 }),
      Chapter.make({ number: 118, numberOfVerses: 29 }),
      Chapter.make({ number: 119, numberOfVerses: 176 }),
      Chapter.make({ number: 120, numberOfVerses: 7 }),
      Chapter.make({ number: 121, numberOfVerses: 8 }),
      Chapter.make({ number: 122, numberOfVerses: 9 }),
      Chapter.make({ number: 123, numberOfVerses: 4 }),
      Chapter.make({ number: 124, numberOfVerses: 8 }),
      Chapter.make({ number: 125, numberOfVerses: 5 }),
      Chapter.make({ number: 126, numberOfVerses: 6 }),
      Chapter.make({ number: 127, numberOfVerses: 5 }),
      Chapter.make({ number: 128, numberOfVerses: 6 }),
      Chapter.make({ number: 129, numberOfVerses: 8 }),
      Chapter.make({ number: 130, numberOfVerses: 8 }),
      Chapter.make({ number: 131, numberOfVerses: 3 }),
      Chapter.make({ number: 132, numberOfVerses: 18 }),
      Chapter.make({ number: 133, numberOfVerses: 3 }),
      Chapter.make({ number: 134, numberOfVerses: 3 }),
      Chapter.make({ number: 135, numberOfVerses: 21 }),
      Chapter.make({ number: 136, numberOfVerses: 26 }),
      Chapter.make({ number: 137, numberOfVerses: 9 }),
      Chapter.make({ number: 138, numberOfVerses: 8 }),
      Chapter.make({ number: 139, numberOfVerses: 24 }),
      Chapter.make({ number: 140, numberOfVerses: 13 }),
      Chapter.make({ number: 141, numberOfVerses: 10 }),
      Chapter.make({ number: 142, numberOfVerses: 7 }),
      Chapter.make({ number: 143, numberOfVerses: 12 }),
      Chapter.make({ number: 144, numberOfVerses: 15 }),
      Chapter.make({ number: 145, numberOfVerses: 21 }),
      Chapter.make({ number: 146, numberOfVerses: 10 }),
      Chapter.make({ number: 147, numberOfVerses: 20 }),
      Chapter.make({ number: 148, numberOfVerses: 14 }),
      Chapter.make({ number: 149, numberOfVerses: 9 }),
      Chapter.make({ number: 150, numberOfVerses: 6 }),
    ],
    fullName: "The Book of Psalms",
  }),
  BibleBook.make({
    name: "Proverbs",
    author: "Solomon and others",
    description: "Wisdom for daily living",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 33 }),
      Chapter.make({ number: 2, numberOfVerses: 22 }),
      Chapter.make({ number: 3, numberOfVerses: 35 }),
      Chapter.make({ number: 4, numberOfVerses: 27 }),
      Chapter.make({ number: 5, numberOfVerses: 23 }),
      Chapter.make({ number: 6, numberOfVerses: 35 }),
      Chapter.make({ number: 7, numberOfVerses: 27 }),
      Chapter.make({ number: 8, numberOfVerses: 36 }),
      Chapter.make({ number: 9, numberOfVerses: 18 }),
      Chapter.make({ number: 10, numberOfVerses: 32 }),
      Chapter.make({ number: 11, numberOfVerses: 31 }),
      Chapter.make({ number: 12, numberOfVerses: 28 }),
      Chapter.make({ number: 13, numberOfVerses: 25 }),
      Chapter.make({ number: 14, numberOfVerses: 35 }),
      Chapter.make({ number: 15, numberOfVerses: 33 }),
      Chapter.make({ number: 16, numberOfVerses: 33 }),
      Chapter.make({ number: 17, numberOfVerses: 28 }),
      Chapter.make({ number: 18, numberOfVerses: 24 }),
      Chapter.make({ number: 19, numberOfVerses: 29 }),
      Chapter.make({ number: 20, numberOfVerses: 30 }),
      Chapter.make({ number: 21, numberOfVerses: 31 }),
      Chapter.make({ number: 22, numberOfVerses: 29 }),
      Chapter.make({ number: 23, numberOfVerses: 35 }),
      Chapter.make({ number: 24, numberOfVerses: 34 }),
      Chapter.make({ number: 25, numberOfVerses: 28 }),
      Chapter.make({ number: 26, numberOfVerses: 28 }),
      Chapter.make({ number: 27, numberOfVerses: 27 }),
      Chapter.make({ number: 28, numberOfVerses: 28 }),
      Chapter.make({ number: 29, numberOfVerses: 27 }),
      Chapter.make({ number: 30, numberOfVerses: 33 }),
      Chapter.make({ number: 31, numberOfVerses: 31 }),
    ],
    fullName: "The Proverbs",
  }),
  BibleBook.make({
    name: "Ecclesiastes",
    author: "Solomon",
    description: "The search for meaning in life",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 18 }),
      Chapter.make({ number: 2, numberOfVerses: 26 }),
      Chapter.make({ number: 3, numberOfVerses: 22 }),
      Chapter.make({ number: 4, numberOfVerses: 16 }),
      Chapter.make({ number: 5, numberOfVerses: 20 }),
      Chapter.make({ number: 6, numberOfVerses: 12 }),
      Chapter.make({ number: 7, numberOfVerses: 29 }),
      Chapter.make({ number: 8, numberOfVerses: 17 }),
      Chapter.make({ number: 9, numberOfVerses: 18 }),
      Chapter.make({ number: 10, numberOfVerses: 20 }),
      Chapter.make({ number: 11, numberOfVerses: 10 }),
      Chapter.make({ number: 12, numberOfVerses: 14 }),
    ],
    fullName: "Ecclesiastes",
  }),
  BibleBook.make({
    name: "Song of Solomon",
    author: "Solomon",
    description: "A celebration of love and marriage",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 17 }),
      Chapter.make({ number: 2, numberOfVerses: 17 }),
      Chapter.make({ number: 3, numberOfVerses: 11 }),
      Chapter.make({ number: 4, numberOfVerses: 16 }),
      Chapter.make({ number: 5, numberOfVerses: 16 }),
      Chapter.make({ number: 6, numberOfVerses: 13 }),
      Chapter.make({ number: 7, numberOfVerses: 13 }),
      Chapter.make({ number: 8, numberOfVerses: 14 }),
    ],
    fullName: "The Song of Solomon",
  }),
  BibleBook.make({
    name: "Isaiah",
    author: "Isaiah",
    description: "Prophecies of judgment and the coming Messiah",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 31 }),
      Chapter.make({ number: 2, numberOfVerses: 22 }),
      Chapter.make({ number: 3, numberOfVerses: 26 }),
      Chapter.make({ number: 4, numberOfVerses: 6 }),
      Chapter.make({ number: 5, numberOfVerses: 30 }),
      Chapter.make({ number: 6, numberOfVerses: 13 }),
      Chapter.make({ number: 7, numberOfVerses: 25 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 21 }),
      Chapter.make({ number: 10, numberOfVerses: 34 }),
      Chapter.make({ number: 11, numberOfVerses: 16 }),
      Chapter.make({ number: 12, numberOfVerses: 6 }),
      Chapter.make({ number: 13, numberOfVerses: 22 }),
      Chapter.make({ number: 14, numberOfVerses: 32 }),
      Chapter.make({ number: 15, numberOfVerses: 9 }),
      Chapter.make({ number: 16, numberOfVerses: 14 }),
      Chapter.make({ number: 17, numberOfVerses: 14 }),
      Chapter.make({ number: 18, numberOfVerses: 7 }),
      Chapter.make({ number: 19, numberOfVerses: 25 }),
      Chapter.make({ number: 20, numberOfVerses: 6 }),
      Chapter.make({ number: 21, numberOfVerses: 17 }),
      Chapter.make({ number: 22, numberOfVerses: 25 }),
      Chapter.make({ number: 23, numberOfVerses: 18 }),
      Chapter.make({ number: 24, numberOfVerses: 23 }),
      Chapter.make({ number: 25, numberOfVerses: 12 }),
      Chapter.make({ number: 26, numberOfVerses: 21 }),
      Chapter.make({ number: 27, numberOfVerses: 13 }),
      Chapter.make({ number: 28, numberOfVerses: 29 }),
      Chapter.make({ number: 29, numberOfVerses: 24 }),
      Chapter.make({ number: 30, numberOfVerses: 33 }),
      Chapter.make({ number: 31, numberOfVerses: 9 }),
      Chapter.make({ number: 32, numberOfVerses: 20 }),
      Chapter.make({ number: 33, numberOfVerses: 24 }),
      Chapter.make({ number: 34, numberOfVerses: 17 }),
      Chapter.make({ number: 35, numberOfVerses: 10 }),
      Chapter.make({ number: 36, numberOfVerses: 22 }),
      Chapter.make({ number: 37, numberOfVerses: 38 }),
      Chapter.make({ number: 38, numberOfVerses: 22 }),
      Chapter.make({ number: 39, numberOfVerses: 8 }),
      Chapter.make({ number: 40, numberOfVerses: 31 }),
      Chapter.make({ number: 41, numberOfVerses: 29 }),
      Chapter.make({ number: 42, numberOfVerses: 25 }),
      Chapter.make({ number: 43, numberOfVerses: 28 }),
      Chapter.make({ number: 44, numberOfVerses: 28 }),
      Chapter.make({ number: 45, numberOfVerses: 25 }),
      Chapter.make({ number: 46, numberOfVerses: 13 }),
      Chapter.make({ number: 47, numberOfVerses: 15 }),
      Chapter.make({ number: 48, numberOfVerses: 22 }),
      Chapter.make({ number: 49, numberOfVerses: 26 }),
      Chapter.make({ number: 50, numberOfVerses: 11 }),
      Chapter.make({ number: 51, numberOfVerses: 23 }),
      Chapter.make({ number: 52, numberOfVerses: 15 }),
      Chapter.make({ number: 53, numberOfVerses: 12 }),
      Chapter.make({ number: 54, numberOfVerses: 17 }),
      Chapter.make({ number: 55, numberOfVerses: 13 }),
      Chapter.make({ number: 56, numberOfVerses: 12 }),
      Chapter.make({ number: 57, numberOfVerses: 21 }),
      Chapter.make({ number: 58, numberOfVerses: 14 }),
      Chapter.make({ number: 59, numberOfVerses: 21 }),
      Chapter.make({ number: 60, numberOfVerses: 22 }),
      Chapter.make({ number: 61, numberOfVerses: 11 }),
      Chapter.make({ number: 62, numberOfVerses: 12 }),
      Chapter.make({ number: 63, numberOfVerses: 19 }),
      Chapter.make({ number: 64, numberOfVerses: 12 }),
      Chapter.make({ number: 65, numberOfVerses: 25 }),
      Chapter.make({ number: 66, numberOfVerses: 24 }),
    ],
    fullName: "The Book of the Prophet Isaiah",
  }),
  BibleBook.make({
    name: "Jeremiah",
    author: "Jeremiah",
    description: "Warnings of judgment and calls to repentance",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 19 }),
      Chapter.make({ number: 2, numberOfVerses: 37 }),
      Chapter.make({ number: 3, numberOfVerses: 25 }),
      Chapter.make({ number: 4, numberOfVerses: 31 }),
      Chapter.make({ number: 5, numberOfVerses: 31 }),
      Chapter.make({ number: 6, numberOfVerses: 30 }),
      Chapter.make({ number: 7, numberOfVerses: 34 }),
      Chapter.make({ number: 8, numberOfVerses: 22 }),
      Chapter.make({ number: 9, numberOfVerses: 26 }),
      Chapter.make({ number: 10, numberOfVerses: 25 }),
      Chapter.make({ number: 11, numberOfVerses: 23 }),
      Chapter.make({ number: 12, numberOfVerses: 17 }),
      Chapter.make({ number: 13, numberOfVerses: 27 }),
      Chapter.make({ number: 14, numberOfVerses: 22 }),
      Chapter.make({ number: 15, numberOfVerses: 21 }),
      Chapter.make({ number: 16, numberOfVerses: 21 }),
      Chapter.make({ number: 17, numberOfVerses: 27 }),
      Chapter.make({ number: 18, numberOfVerses: 23 }),
      Chapter.make({ number: 19, numberOfVerses: 15 }),
      Chapter.make({ number: 20, numberOfVerses: 18 }),
      Chapter.make({ number: 21, numberOfVerses: 14 }),
      Chapter.make({ number: 22, numberOfVerses: 30 }),
      Chapter.make({ number: 23, numberOfVerses: 40 }),
      Chapter.make({ number: 24, numberOfVerses: 10 }),
      Chapter.make({ number: 25, numberOfVerses: 38 }),
      Chapter.make({ number: 26, numberOfVerses: 24 }),
      Chapter.make({ number: 27, numberOfVerses: 22 }),
      Chapter.make({ number: 28, numberOfVerses: 17 }),
      Chapter.make({ number: 29, numberOfVerses: 32 }),
      Chapter.make({ number: 30, numberOfVerses: 24 }),
      Chapter.make({ number: 31, numberOfVerses: 40 }),
      Chapter.make({ number: 32, numberOfVerses: 44 }),
      Chapter.make({ number: 33, numberOfVerses: 26 }),
      Chapter.make({ number: 34, numberOfVerses: 22 }),
      Chapter.make({ number: 35, numberOfVerses: 19 }),
      Chapter.make({ number: 36, numberOfVerses: 32 }),
      Chapter.make({ number: 37, numberOfVerses: 21 }),
      Chapter.make({ number: 38, numberOfVerses: 28 }),
      Chapter.make({ number: 39, numberOfVerses: 18 }),
      Chapter.make({ number: 40, numberOfVerses: 16 }),
      Chapter.make({ number: 41, numberOfVerses: 18 }),
      Chapter.make({ number: 42, numberOfVerses: 22 }),
      Chapter.make({ number: 43, numberOfVerses: 13 }),
      Chapter.make({ number: 44, numberOfVerses: 30 }),
      Chapter.make({ number: 45, numberOfVerses: 5 }),
      Chapter.make({ number: 46, numberOfVerses: 28 }),
      Chapter.make({ number: 47, numberOfVerses: 7 }),
      Chapter.make({ number: 48, numberOfVerses: 47 }),
      Chapter.make({ number: 49, numberOfVerses: 39 }),
      Chapter.make({ number: 50, numberOfVerses: 46 }),
      Chapter.make({ number: 51, numberOfVerses: 64 }),
      Chapter.make({ number: 52, numberOfVerses: 34 }),
    ],
    fullName: "The Book of the Prophet Jeremiah",
  }),
  BibleBook.make({
    name: "Lamentations",
    author: "Jeremiah",
    description: "Mourning over Jerusalem's destruction",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 22 }),
      Chapter.make({ number: 2, numberOfVerses: 22 }),
      Chapter.make({ number: 3, numberOfVerses: 66 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
      Chapter.make({ number: 5, numberOfVerses: 22 }),
    ],
    fullName: "The Lamentations of Jeremiah",
  }),
  BibleBook.make({
    name: "Ezekiel",
    author: "Ezekiel",
    description: "Visions of God's glory and restoration",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 28 }),
      Chapter.make({ number: 2, numberOfVerses: 10 }),
      Chapter.make({ number: 3, numberOfVerses: 27 }),
      Chapter.make({ number: 4, numberOfVerses: 17 }),
      Chapter.make({ number: 5, numberOfVerses: 17 }),
      Chapter.make({ number: 6, numberOfVerses: 14 }),
      Chapter.make({ number: 7, numberOfVerses: 27 }),
      Chapter.make({ number: 8, numberOfVerses: 18 }),
      Chapter.make({ number: 9, numberOfVerses: 11 }),
      Chapter.make({ number: 10, numberOfVerses: 22 }),
      Chapter.make({ number: 11, numberOfVerses: 25 }),
      Chapter.make({ number: 12, numberOfVerses: 28 }),
      Chapter.make({ number: 13, numberOfVerses: 23 }),
      Chapter.make({ number: 14, numberOfVerses: 23 }),
      Chapter.make({ number: 15, numberOfVerses: 8 }),
      Chapter.make({ number: 16, numberOfVerses: 63 }),
      Chapter.make({ number: 17, numberOfVerses: 24 }),
      Chapter.make({ number: 18, numberOfVerses: 32 }),
      Chapter.make({ number: 19, numberOfVerses: 14 }),
      Chapter.make({ number: 20, numberOfVerses: 49 }),
      Chapter.make({ number: 21, numberOfVerses: 32 }),
      Chapter.make({ number: 22, numberOfVerses: 31 }),
      Chapter.make({ number: 23, numberOfVerses: 49 }),
      Chapter.make({ number: 24, numberOfVerses: 27 }),
      Chapter.make({ number: 25, numberOfVerses: 17 }),
      Chapter.make({ number: 26, numberOfVerses: 21 }),
      Chapter.make({ number: 27, numberOfVerses: 36 }),
      Chapter.make({ number: 28, numberOfVerses: 26 }),
      Chapter.make({ number: 29, numberOfVerses: 21 }),
      Chapter.make({ number: 30, numberOfVerses: 26 }),
      Chapter.make({ number: 31, numberOfVerses: 18 }),
      Chapter.make({ number: 32, numberOfVerses: 32 }),
      Chapter.make({ number: 33, numberOfVerses: 33 }),
      Chapter.make({ number: 34, numberOfVerses: 31 }),
      Chapter.make({ number: 35, numberOfVerses: 15 }),
      Chapter.make({ number: 36, numberOfVerses: 38 }),
      Chapter.make({ number: 37, numberOfVerses: 28 }),
      Chapter.make({ number: 38, numberOfVerses: 23 }),
      Chapter.make({ number: 39, numberOfVerses: 29 }),
      Chapter.make({ number: 40, numberOfVerses: 49 }),
      Chapter.make({ number: 41, numberOfVerses: 26 }),
      Chapter.make({ number: 42, numberOfVerses: 20 }),
      Chapter.make({ number: 43, numberOfVerses: 27 }),
      Chapter.make({ number: 44, numberOfVerses: 31 }),
      Chapter.make({ number: 45, numberOfVerses: 25 }),
      Chapter.make({ number: 46, numberOfVerses: 24 }),
      Chapter.make({ number: 47, numberOfVerses: 23 }),
      Chapter.make({ number: 48, numberOfVerses: 35 }),
    ],
    fullName: "The Book of the Prophet Ezekiel",
  }),
  BibleBook.make({
    name: "Daniel",
    author: "Daniel",
    description: "Faithfulness in exile and prophetic visions",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 21 }),
      Chapter.make({ number: 2, numberOfVerses: 49 }),
      Chapter.make({ number: 3, numberOfVerses: 30 }),
      Chapter.make({ number: 4, numberOfVerses: 37 }),
      Chapter.make({ number: 5, numberOfVerses: 31 }),
      Chapter.make({ number: 6, numberOfVerses: 28 }),
      Chapter.make({ number: 7, numberOfVerses: 28 }),
      Chapter.make({ number: 8, numberOfVerses: 27 }),
      Chapter.make({ number: 9, numberOfVerses: 27 }),
      Chapter.make({ number: 10, numberOfVerses: 21 }),
      Chapter.make({ number: 11, numberOfVerses: 45 }),
      Chapter.make({ number: 12, numberOfVerses: 13 }),
    ],
    fullName: "The Book of Daniel",
  }),
  BibleBook.make({
    name: "Hosea",
    author: "Hosea",
    description: "God's faithful love despite Israel's unfaithfulness",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 11 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 5 }),
      Chapter.make({ number: 4, numberOfVerses: 19 }),
      Chapter.make({ number: 5, numberOfVerses: 15 }),
      Chapter.make({ number: 6, numberOfVerses: 11 }),
      Chapter.make({ number: 7, numberOfVerses: 16 }),
      Chapter.make({ number: 8, numberOfVerses: 14 }),
      Chapter.make({ number: 9, numberOfVerses: 17 }),
      Chapter.make({ number: 10, numberOfVerses: 15 }),
      Chapter.make({ number: 11, numberOfVerses: 12 }),
      Chapter.make({ number: 12, numberOfVerses: 14 }),
      Chapter.make({ number: 13, numberOfVerses: 16 }),
      Chapter.make({ number: 14, numberOfVerses: 9 }),
    ],
    fullName: "Hosea",
  }),
  BibleBook.make({
    name: "Joel",
    author: "Joel",
    description: "The Day of the Lord and spiritual renewal",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 20 }),
      Chapter.make({ number: 2, numberOfVerses: 32 }),
      Chapter.make({ number: 3, numberOfVerses: 21 }),
    ],
    fullName: "Joel",
  }),
  BibleBook.make({
    name: "Amos",
    author: "Amos",
    description: "God's judgment on injustice",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 15 }),
      Chapter.make({ number: 2, numberOfVerses: 16 }),
      Chapter.make({ number: 3, numberOfVerses: 15 }),
      Chapter.make({ number: 4, numberOfVerses: 13 }),
      Chapter.make({ number: 5, numberOfVerses: 27 }),
      Chapter.make({ number: 6, numberOfVerses: 14 }),
      Chapter.make({ number: 7, numberOfVerses: 17 }),
      Chapter.make({ number: 8, numberOfVerses: 14 }),
      Chapter.make({ number: 9, numberOfVerses: 15 }),
    ],
    fullName: "Amos",
  }),
  BibleBook.make({
    name: "Obadiah",
    author: "Obadiah",
    description: "Judgment on Edom",
    chapters: [Chapter.make({ number: 1, numberOfVerses: 21 })],
    fullName: "Obadiah",
  }),
  BibleBook.make({
    name: "Jonah",
    author: "Jonah",
    description: "God's mercy extends to all nations",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 17 }),
      Chapter.make({ number: 2, numberOfVerses: 10 }),
      Chapter.make({ number: 3, numberOfVerses: 10 }),
      Chapter.make({ number: 4, numberOfVerses: 11 }),
    ],
    fullName: "Jonah",
  }),
  BibleBook.make({
    name: "Micah",
    author: "Micah",
    description: "Justice, mercy, and the coming ruler",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 16 }),
      Chapter.make({ number: 2, numberOfVerses: 13 }),
      Chapter.make({ number: 3, numberOfVerses: 12 }),
      Chapter.make({ number: 4, numberOfVerses: 13 }),
      Chapter.make({ number: 5, numberOfVerses: 15 }),
      Chapter.make({ number: 6, numberOfVerses: 16 }),
      Chapter.make({ number: 7, numberOfVerses: 20 }),
    ],
    fullName: "Micah",
  }),
  BibleBook.make({
    name: "Nahum",
    author: "Nahum",
    description: "God's judgment on Nineveh",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 15 }),
      Chapter.make({ number: 2, numberOfVerses: 13 }),
      Chapter.make({ number: 3, numberOfVerses: 19 }),
    ],
    fullName: "Nahum",
  }),
  BibleBook.make({
    name: "Habakkuk",
    author: "Habakkuk",
    description: "Living by faith in difficult times",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 17 }),
      Chapter.make({ number: 2, numberOfVerses: 20 }),
      Chapter.make({ number: 3, numberOfVerses: 19 }),
    ],
    fullName: "Habakkuk",
  }),
  BibleBook.make({
    name: "Zephaniah",
    author: "Zephaniah",
    description: "The Day of the Lord and restoration",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 18 }),
      Chapter.make({ number: 2, numberOfVerses: 15 }),
      Chapter.make({ number: 3, numberOfVerses: 20 }),
    ],
    fullName: "Zephaniah",
  }),
  BibleBook.make({
    name: "Haggai",
    author: "Haggai",
    description: "Rebuilding the temple with right priorities",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 15 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
    ],
    fullName: "Haggai",
  }),
  BibleBook.make({
    name: "Zechariah",
    author: "Zechariah",
    description: "Visions of restoration and the Messiah",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 21 }),
      Chapter.make({ number: 2, numberOfVerses: 13 }),
      Chapter.make({ number: 3, numberOfVerses: 10 }),
      Chapter.make({ number: 4, numberOfVerses: 14 }),
      Chapter.make({ number: 5, numberOfVerses: 11 }),
      Chapter.make({ number: 6, numberOfVerses: 15 }),
      Chapter.make({ number: 7, numberOfVerses: 14 }),
      Chapter.make({ number: 8, numberOfVerses: 23 }),
      Chapter.make({ number: 9, numberOfVerses: 17 }),
      Chapter.make({ number: 10, numberOfVerses: 12 }),
      Chapter.make({ number: 11, numberOfVerses: 17 }),
      Chapter.make({ number: 12, numberOfVerses: 14 }),
      Chapter.make({ number: 13, numberOfVerses: 9 }),
      Chapter.make({ number: 14, numberOfVerses: 21 }),
    ],
    fullName: "Zechariah",
  }),
  BibleBook.make({
    name: "Malachi",
    author: "Malachi",
    description: "A call to covenant faithfulness",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 14 }),
      Chapter.make({ number: 2, numberOfVerses: 17 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
      Chapter.make({ number: 4, numberOfVerses: 6 }),
    ],
    fullName: "Malachi",
  }),
  BibleBook.make({
    name: "Matthew",
    author: "atthew",
    description: "Jesus as the promised Messiah and King",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 25 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 17 }),
      Chapter.make({ number: 4, numberOfVerses: 25 }),
      Chapter.make({ number: 5, numberOfVerses: 48 }),
      Chapter.make({ number: 6, numberOfVerses: 34 }),
      Chapter.make({ number: 7, numberOfVerses: 29 }),
      Chapter.make({ number: 8, numberOfVerses: 34 }),
      Chapter.make({ number: 9, numberOfVerses: 38 }),
      Chapter.make({ number: 10, numberOfVerses: 42 }),
      Chapter.make({ number: 11, numberOfVerses: 30 }),
      Chapter.make({ number: 12, numberOfVerses: 50 }),
      Chapter.make({ number: 13, numberOfVerses: 58 }),
      Chapter.make({ number: 14, numberOfVerses: 36 }),
      Chapter.make({ number: 15, numberOfVerses: 39 }),
      Chapter.make({ number: 16, numberOfVerses: 28 }),
      Chapter.make({ number: 17, numberOfVerses: 27 }),
      Chapter.make({ number: 18, numberOfVerses: 35 }),
      Chapter.make({ number: 19, numberOfVerses: 30 }),
      Chapter.make({ number: 20, numberOfVerses: 34 }),
      Chapter.make({ number: 21, numberOfVerses: 46 }),
      Chapter.make({ number: 22, numberOfVerses: 46 }),
      Chapter.make({ number: 23, numberOfVerses: 39 }),
      Chapter.make({ number: 24, numberOfVerses: 51 }),
      Chapter.make({ number: 25, numberOfVerses: 46 }),
      Chapter.make({ number: 26, numberOfVerses: 75 }),
      Chapter.make({ number: 27, numberOfVerses: 66 }),
      Chapter.make({ number: 28, numberOfVerses: 20 }),
    ],
    fullName: "The Gospel According to Saint Matthew",
  }),
  BibleBook.make({
    name: "Mark",
    author: "ohn Mark",
    description: "Jesus as the suffering Servant",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 45 }),
      Chapter.make({ number: 2, numberOfVerses: 28 }),
      Chapter.make({ number: 3, numberOfVerses: 35 }),
      Chapter.make({ number: 4, numberOfVerses: 41 }),
      Chapter.make({ number: 5, numberOfVerses: 43 }),
      Chapter.make({ number: 6, numberOfVerses: 56 }),
      Chapter.make({ number: 7, numberOfVerses: 37 }),
      Chapter.make({ number: 8, numberOfVerses: 38 }),
      Chapter.make({ number: 9, numberOfVerses: 50 }),
      Chapter.make({ number: 10, numberOfVerses: 52 }),
      Chapter.make({ number: 11, numberOfVerses: 33 }),
      Chapter.make({ number: 12, numberOfVerses: 44 }),
      Chapter.make({ number: 13, numberOfVerses: 37 }),
      Chapter.make({ number: 14, numberOfVerses: 72 }),
      Chapter.make({ number: 15, numberOfVerses: 47 }),
      Chapter.make({ number: 16, numberOfVerses: 20 }),
    ],
    fullName: "The Gospel According to Saint Mark",
  }),
  BibleBook.make({
    name: "Luke",
    author: "uke",
    description: "Jesus as the Son of Man for all people",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 80 }),
      Chapter.make({ number: 2, numberOfVerses: 52 }),
      Chapter.make({ number: 3, numberOfVerses: 38 }),
      Chapter.make({ number: 4, numberOfVerses: 44 }),
      Chapter.make({ number: 5, numberOfVerses: 39 }),
      Chapter.make({ number: 6, numberOfVerses: 49 }),
      Chapter.make({ number: 7, numberOfVerses: 50 }),
      Chapter.make({ number: 8, numberOfVerses: 56 }),
      Chapter.make({ number: 9, numberOfVerses: 62 }),
      Chapter.make({ number: 10, numberOfVerses: 42 }),
      Chapter.make({ number: 11, numberOfVerses: 54 }),
      Chapter.make({ number: 12, numberOfVerses: 59 }),
      Chapter.make({ number: 13, numberOfVerses: 35 }),
      Chapter.make({ number: 14, numberOfVerses: 35 }),
      Chapter.make({ number: 15, numberOfVerses: 32 }),
      Chapter.make({ number: 16, numberOfVerses: 31 }),
      Chapter.make({ number: 17, numberOfVerses: 37 }),
      Chapter.make({ number: 18, numberOfVerses: 43 }),
      Chapter.make({ number: 19, numberOfVerses: 48 }),
      Chapter.make({ number: 20, numberOfVerses: 47 }),
      Chapter.make({ number: 21, numberOfVerses: 38 }),
      Chapter.make({ number: 22, numberOfVerses: 71 }),
      Chapter.make({ number: 23, numberOfVerses: 56 }),
      Chapter.make({ number: 24, numberOfVerses: 53 }),
    ],
    fullName: "The Gospel According to Saint Luke",
  }),
  BibleBook.make({
    name: "John",
    author: "John",
    description: "Jesus as the Son of God",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 51 }),
      Chapter.make({ number: 2, numberOfVerses: 25 }),
      Chapter.make({ number: 3, numberOfVerses: 36 }),
      Chapter.make({ number: 4, numberOfVerses: 54 }),
      Chapter.make({ number: 5, numberOfVerses: 47 }),
      Chapter.make({ number: 6, numberOfVerses: 71 }),
      Chapter.make({ number: 7, numberOfVerses: 53 }),
      Chapter.make({ number: 8, numberOfVerses: 59 }),
      Chapter.make({ number: 9, numberOfVerses: 41 }),
      Chapter.make({ number: 10, numberOfVerses: 42 }),
      Chapter.make({ number: 11, numberOfVerses: 57 }),
      Chapter.make({ number: 12, numberOfVerses: 50 }),
      Chapter.make({ number: 13, numberOfVerses: 38 }),
      Chapter.make({ number: 14, numberOfVerses: 31 }),
      Chapter.make({ number: 15, numberOfVerses: 27 }),
      Chapter.make({ number: 16, numberOfVerses: 33 }),
      Chapter.make({ number: 17, numberOfVerses: 26 }),
      Chapter.make({ number: 18, numberOfVerses: 40 }),
      Chapter.make({ number: 19, numberOfVerses: 42 }),
      Chapter.make({ number: 20, numberOfVerses: 31 }),
      Chapter.make({ number: 21, numberOfVerses: 25 }),
    ],
    fullName: "The Gospel According to Saint John",
  }),
  BibleBook.make({
    name: "Acts",
    author: "uke",
    description: "The birth and growth of the early church",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 26 }),
      Chapter.make({ number: 2, numberOfVerses: 47 }),
      Chapter.make({ number: 3, numberOfVerses: 26 }),
      Chapter.make({ number: 4, numberOfVerses: 37 }),
      Chapter.make({ number: 5, numberOfVerses: 42 }),
      Chapter.make({ number: 6, numberOfVerses: 15 }),
      Chapter.make({ number: 7, numberOfVerses: 60 }),
      Chapter.make({ number: 8, numberOfVerses: 40 }),
      Chapter.make({ number: 9, numberOfVerses: 43 }),
      Chapter.make({ number: 10, numberOfVerses: 48 }),
      Chapter.make({ number: 11, numberOfVerses: 30 }),
      Chapter.make({ number: 12, numberOfVerses: 25 }),
      Chapter.make({ number: 13, numberOfVerses: 52 }),
      Chapter.make({ number: 14, numberOfVerses: 28 }),
      Chapter.make({ number: 15, numberOfVerses: 41 }),
      Chapter.make({ number: 16, numberOfVerses: 40 }),
      Chapter.make({ number: 17, numberOfVerses: 34 }),
      Chapter.make({ number: 18, numberOfVerses: 28 }),
      Chapter.make({ number: 19, numberOfVerses: 41 }),
      Chapter.make({ number: 20, numberOfVerses: 38 }),
      Chapter.make({ number: 21, numberOfVerses: 40 }),
      Chapter.make({ number: 22, numberOfVerses: 30 }),
      Chapter.make({ number: 23, numberOfVerses: 35 }),
      Chapter.make({ number: 24, numberOfVerses: 27 }),
      Chapter.make({ number: 25, numberOfVerses: 27 }),
      Chapter.make({ number: 26, numberOfVerses: 32 }),
      Chapter.make({ number: 27, numberOfVerses: 44 }),
      Chapter.make({ number: 28, numberOfVerses: 31 }),
    ],
    fullName: "The Acts of the Apostles",
  }),
  BibleBook.make({
    name: "Romans",
    author: "aul",
    description: "The gospel of justification by faith",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 32 }),
      Chapter.make({ number: 2, numberOfVerses: 29 }),
      Chapter.make({ number: 3, numberOfVerses: 31 }),
      Chapter.make({ number: 4, numberOfVerses: 25 }),
      Chapter.make({ number: 5, numberOfVerses: 21 }),
      Chapter.make({ number: 6, numberOfVerses: 23 }),
      Chapter.make({ number: 7, numberOfVerses: 25 }),
      Chapter.make({ number: 8, numberOfVerses: 39 }),
      Chapter.make({ number: 9, numberOfVerses: 33 }),
      Chapter.make({ number: 10, numberOfVerses: 21 }),
      Chapter.make({ number: 11, numberOfVerses: 36 }),
      Chapter.make({ number: 12, numberOfVerses: 21 }),
      Chapter.make({ number: 13, numberOfVerses: 14 }),
      Chapter.make({ number: 14, numberOfVerses: 23 }),
      Chapter.make({ number: 15, numberOfVerses: 33 }),
      Chapter.make({ number: 16, numberOfVerses: 27 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Romans",
  }),
  BibleBook.make({
    name: "1 Corinthians",
    author: "aul",
    description: "Addressing problems in the Corinthian church",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 31 }),
      Chapter.make({ number: 2, numberOfVerses: 16 }),
      Chapter.make({ number: 3, numberOfVerses: 23 }),
      Chapter.make({ number: 4, numberOfVerses: 21 }),
      Chapter.make({ number: 5, numberOfVerses: 13 }),
      Chapter.make({ number: 6, numberOfVerses: 20 }),
      Chapter.make({ number: 7, numberOfVerses: 40 }),
      Chapter.make({ number: 8, numberOfVerses: 13 }),
      Chapter.make({ number: 9, numberOfVerses: 27 }),
      Chapter.make({ number: 10, numberOfVerses: 33 }),
      Chapter.make({ number: 11, numberOfVerses: 34 }),
      Chapter.make({ number: 12, numberOfVerses: 31 }),
      Chapter.make({ number: 13, numberOfVerses: 13 }),
      Chapter.make({ number: 14, numberOfVerses: 40 }),
      Chapter.make({ number: 15, numberOfVerses: 58 }),
      Chapter.make({ number: 16, numberOfVerses: 24 }),
    ],
    fullName: "The First Epistle of Paul the Apostle to the Corinthians",
  }),
  BibleBook.make({
    name: "2 Corinthians",
    author: "aul",
    description: "Paul's defense of his apostolic ministry",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 24 }),
      Chapter.make({ number: 2, numberOfVerses: 17 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
      Chapter.make({ number: 4, numberOfVerses: 18 }),
      Chapter.make({ number: 5, numberOfVerses: 21 }),
      Chapter.make({ number: 6, numberOfVerses: 18 }),
      Chapter.make({ number: 7, numberOfVerses: 16 }),
      Chapter.make({ number: 8, numberOfVerses: 24 }),
      Chapter.make({ number: 9, numberOfVerses: 15 }),
      Chapter.make({ number: 10, numberOfVerses: 18 }),
      Chapter.make({ number: 11, numberOfVerses: 33 }),
      Chapter.make({ number: 12, numberOfVerses: 21 }),
      Chapter.make({ number: 13, numberOfVerses: 14 }),
    ],
    fullName: "The Second Epistle of Paul the Apostle to the Corinthians",
  }),
  BibleBook.make({
    name: "Galatians",
    author: "aul",
    description: "Freedom in Christ and justification by faith",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 24 }),
      Chapter.make({ number: 2, numberOfVerses: 21 }),
      Chapter.make({ number: 3, numberOfVerses: 29 }),
      Chapter.make({ number: 4, numberOfVerses: 31 }),
      Chapter.make({ number: 5, numberOfVerses: 26 }),
      Chapter.make({ number: 6, numberOfVerses: 18 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Galatians",
  }),
  BibleBook.make({
    name: "Ephesians",
    author: "aul",
    description: "The church as the body of Christ",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 23 }),
      Chapter.make({ number: 2, numberOfVerses: 22 }),
      Chapter.make({ number: 3, numberOfVerses: 21 }),
      Chapter.make({ number: 4, numberOfVerses: 32 }),
      Chapter.make({ number: 5, numberOfVerses: 33 }),
      Chapter.make({ number: 6, numberOfVerses: 24 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Ephesians",
  }),
  BibleBook.make({
    name: "Philippians",
    author: "aul",
    description: "Joy and unity in Christ",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 30 }),
      Chapter.make({ number: 2, numberOfVerses: 30 }),
      Chapter.make({ number: 3, numberOfVerses: 21 }),
      Chapter.make({ number: 4, numberOfVerses: 23 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Philippians",
  }),
  BibleBook.make({
    name: "Colossians",
    author: "aul",
    description: "The supremacy of Christ",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 29 }),
      Chapter.make({ number: 2, numberOfVerses: 23 }),
      Chapter.make({ number: 3, numberOfVerses: 25 }),
      Chapter.make({ number: 4, numberOfVerses: 18 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Colossians",
  }),
  BibleBook.make({
    name: "1 Thessalonians",
    author: "aul",
    description: "Living for Christ's return",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 10 }),
      Chapter.make({ number: 2, numberOfVerses: 20 }),
      Chapter.make({ number: 3, numberOfVerses: 13 }),
      Chapter.make({ number: 4, numberOfVerses: 18 }),
      Chapter.make({ number: 5, numberOfVerses: 28 }),
    ],
    fullName: "The First Epistle of Paul the Apostle to the Thessalonians",
  }),
  BibleBook.make({
    name: "2 Thessalonians",
    author: "aul",
    description: "Correcting misunderstandings about Christ's return",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 12 }),
      Chapter.make({ number: 2, numberOfVerses: 17 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
    ],
    fullName: "The Second Epistle of Paul the Apostle to the Thessalonians",
  }),
  BibleBook.make({
    name: "1 Timothy",
    author: "aul",
    description: "Instructions for church leadership",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 20 }),
      Chapter.make({ number: 2, numberOfVerses: 15 }),
      Chapter.make({ number: 3, numberOfVerses: 16 }),
      Chapter.make({ number: 4, numberOfVerses: 16 }),
      Chapter.make({ number: 5, numberOfVerses: 25 }),
      Chapter.make({ number: 6, numberOfVerses: 21 }),
    ],
    fullName: "The First Epistle of Paul the Apostle to Timothy",
  }),
  BibleBook.make({
    name: "2 Timothy",
    author: "aul",
    description: "Paul's final charge to Timothy",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 18 }),
      Chapter.make({ number: 2, numberOfVerses: 26 }),
      Chapter.make({ number: 3, numberOfVerses: 17 }),
      Chapter.make({ number: 4, numberOfVerses: 22 }),
    ],
    fullName: "The Second Epistle of Paul the Apostle to Timothy",
  }),
  BibleBook.make({
    name: "Titus",
    author: "aul",
    description: "Church order and sound doctrine",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 16 }),
      Chapter.make({ number: 2, numberOfVerses: 15 }),
      Chapter.make({ number: 3, numberOfVerses: 15 }),
    ],
    fullName: "The Epistle of Paul the Apostle to Titus",
  }),
  BibleBook.make({
    name: "Philemon",
    author: "aul",
    description: "A personal appeal for Christian forgiveness",
    chapters: [Chapter.make({ number: 1, numberOfVerses: 25 })],
    fullName: "The Epistle of Paul the Apostle to Philemon",
  }),
  BibleBook.make({
    name: "Hebrews",
    author: "nknown",
    description: "The superiority of Christ and the new covenant",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 14 }),
      Chapter.make({ number: 2, numberOfVerses: 18 }),
      Chapter.make({ number: 3, numberOfVerses: 19 }),
      Chapter.make({ number: 4, numberOfVerses: 16 }),
      Chapter.make({ number: 5, numberOfVerses: 14 }),
      Chapter.make({ number: 6, numberOfVerses: 20 }),
      Chapter.make({ number: 7, numberOfVerses: 28 }),
      Chapter.make({ number: 8, numberOfVerses: 13 }),
      Chapter.make({ number: 9, numberOfVerses: 28 }),
      Chapter.make({ number: 10, numberOfVerses: 39 }),
      Chapter.make({ number: 11, numberOfVerses: 40 }),
      Chapter.make({ number: 12, numberOfVerses: 29 }),
      Chapter.make({ number: 13, numberOfVerses: 25 }),
    ],
    fullName: "The Epistle of Paul the Apostle to the Hebrews",
  }),
  BibleBook.make({
    name: "James",
    author: "ames",
    description: "Practical Christian living and faith in action",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 27 }),
      Chapter.make({ number: 2, numberOfVerses: 26 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
      Chapter.make({ number: 4, numberOfVerses: 17 }),
      Chapter.make({ number: 5, numberOfVerses: 20 }),
    ],
    fullName: "The General Epistle of James",
  }),
  BibleBook.make({
    name: "1 Peter",
    author: "eter",
    description: "Hope and holiness in suffering",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 25 }),
      Chapter.make({ number: 2, numberOfVerses: 25 }),
      Chapter.make({ number: 3, numberOfVerses: 22 }),
      Chapter.make({ number: 4, numberOfVerses: 19 }),
      Chapter.make({ number: 5, numberOfVerses: 14 }),
    ],
    fullName: "The First Epistle General of Peter",
  }),
  BibleBook.make({
    name: "2 Peter",
    author: "eter",
    description: "Warning against false teachers",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 21 }),
      Chapter.make({ number: 2, numberOfVerses: 22 }),
      Chapter.make({ number: 3, numberOfVerses: 18 }),
    ],
    fullName: "The Second General Epistle of Peter",
  }),
  BibleBook.make({
    name: "1 John",
    author: "ohn",
    description: "The assurance of eternal life and love",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 10 }),
      Chapter.make({ number: 2, numberOfVerses: 29 }),
      Chapter.make({ number: 3, numberOfVerses: 24 }),
      Chapter.make({ number: 4, numberOfVerses: 21 }),
      Chapter.make({ number: 5, numberOfVerses: 21 }),
    ],
    fullName: "The First Epistle General of John",
  }),
  BibleBook.make({
    name: "2 John",
    author: "ohn",
    description: "Walking in truth and love",
    chapters: [Chapter.make({ number: 1, numberOfVerses: 13 })],
    fullName: "The Second Epistle General of John",
  }),
  BibleBook.make({
    name: "3 John",
    author: "ohn",
    description: "Hospitality and truth in the church",
    chapters: [Chapter.make({ number: 1, numberOfVerses: 14 })],
    fullName: "The Third Epistle General of John",
  }),
  BibleBook.make({
    name: "Jude",
    author: "Jude",
    description: "Contending for the faith",
    chapters: [Chapter.make({ number: 1, numberOfVerses: 25 })],
    fullName: "The General Epistle of Jude",
  }),
  BibleBook.make({
    name: "Revelation",
    author: "John",
    description: "The ultimate victory of Christ and His kingdom",
    chapters: [
      Chapter.make({ number: 1, numberOfVerses: 20 }),
      Chapter.make({ number: 2, numberOfVerses: 29 }),
      Chapter.make({ number: 3, numberOfVerses: 22 }),
      Chapter.make({ number: 4, numberOfVerses: 11 }),
      Chapter.make({ number: 5, numberOfVerses: 14 }),
      Chapter.make({ number: 6, numberOfVerses: 17 }),
      Chapter.make({ number: 7, numberOfVerses: 17 }),
      Chapter.make({ number: 8, numberOfVerses: 13 }),
      Chapter.make({ number: 9, numberOfVerses: 21 }),
      Chapter.make({ number: 10, numberOfVerses: 11 }),
      Chapter.make({ number: 11, numberOfVerses: 19 }),
      Chapter.make({ number: 12, numberOfVerses: 17 }),
      Chapter.make({ number: 13, numberOfVerses: 18 }),
      Chapter.make({ number: 14, numberOfVerses: 20 }),
      Chapter.make({ number: 15, numberOfVerses: 8 }),
      Chapter.make({ number: 16, numberOfVerses: 21 }),
      Chapter.make({ number: 17, numberOfVerses: 18 }),
      Chapter.make({ number: 18, numberOfVerses: 24 }),
      Chapter.make({ number: 19, numberOfVerses: 21 }),
      Chapter.make({ number: 20, numberOfVerses: 15 }),
      Chapter.make({ number: 21, numberOfVerses: 27 }),
      Chapter.make({ number: 22, numberOfVerses: 21 }),
    ],
    fullName: "The Revelation of Saint John the Devine",
  }),
];
